/* Simmer content. Everything the app shows lives here so it works offline.

   Ingredient rows are [qty, unit, item]. qty is a number so the servings
   stepper can scale it (null = "to taste", never scaled). Nutrition is a rough
   per-serving estimate, labelled "approx." in the app — good enough to compare
   recipes, not to count to the gram. */

/* Every human recipe is pork-free (no pork, bacon, ham, lard or gelatin), and
   none cook with wine. check.js fails the build if one slips in. */

/* Courses in menu order. "Main" is shown as "Mains (entrées)". */
const COURSES = ['Breakfast', 'Appetizer', 'Soup & Salad', 'Main', 'Side', 'Dessert', 'Snack', 'Drink'];
const COURSE_LABEL = { Breakfast: 'Breakfast', Appetizer: 'Appetizers', 'Soup & Salad': 'Soups & Salads', Main: 'Mains (entrées)',
  Side: 'Sides', Dessert: 'Desserts', Snack: 'Snacks', Drink: 'Drinks' };
const DOG_COURSES = ['Treat', 'Topper', 'Meal', 'Enrichment'];
const LEVELS = ['Easy', 'Medium', 'Hard'];
const LEVEL_ICON = { Easy: '🟢', Medium: '🟡', Hard: '🔴' };

/* Listed west to east around the world; "group by cuisine" follows this order. */
const CUISINE_INFO = [
  { id: 'namerican', name: 'North American', region: 'The Americas', emoji: '🍁' },
  { id: 'mexican', name: 'Mexican', region: 'The Americas', emoji: '🌮' },
  { id: 'italian', name: 'Italian', region: 'Europe', emoji: '🍝' },
  { id: 'greek', name: 'Greek & Mediterranean', region: 'Europe', emoji: '🫒' },
  { id: 'nafrican', name: 'North African', region: 'Middle East & Africa', emoji: '🫖' },
  { id: 'mideast', name: 'Middle Eastern', region: 'Middle East & Africa', emoji: '🧆' },
  { id: 'persian', name: 'Persian', region: 'Middle East & Africa', emoji: '🍢' },
  { id: 'indian', name: 'Indian', region: 'South Asia', emoji: '🍛' },
  { id: 'thai', name: 'Thai', region: 'Southeast Asia', emoji: '🌶️' },
  { id: 'viet', name: 'Vietnamese', region: 'Southeast Asia', emoji: '🍜' },
  { id: 'chinese', name: 'Chinese', region: 'East Asia', emoji: '🥢' },
  { id: 'korean', name: 'Korean', region: 'East Asia', emoji: '🍚' },
  { id: 'japanese', name: 'Japanese', region: 'East Asia', emoji: '🍣' },
];

const RECIPES = [
  /* ───────────── Human: breakfast ───────────── */
  { id: 'overnight-oats', kind: 'human', course: 'Breakfast', cuisine: 'namerican', level: 'Easy', emoji: '🥣', title: 'Berry Overnight Oats',
    time: 5, wait: 'overnight', serves: 1, tags: ['vegetarian', 'make-ahead', 'quick'],
    blurb: 'Five minutes the night before, breakfast is waiting in the fridge.',
    kcal: 390, protein: 20,
    ingredients: [[0.5, 'cup', 'rolled oats'], [0.5, 'cup', 'milk (any kind)'], [0.33, 'cup', 'plain Greek yogurt'],
      [1, 'tbsp', 'chia seeds'], [1, 'tsp', 'honey or maple syrup'], [0.5, 'cup', 'mixed berries'], [null, '', 'pinch of cinnamon']],
    steps: ['Stir the oats, milk, yogurt, chia, honey and cinnamon together in a jar.',
      'Fold in half the berries, put the lid on and refrigerate overnight (at least 4 hours).',
      'In the morning, stir, loosen with a splash of milk if thick, and top with the rest of the berries.'],
    tips: ['Keeps 3 days in the fridge — make several jars on Sunday.', 'Swap berries for grated apple + cinnamon in winter.'] },

  { id: 'egg-muffins', kind: 'human', course: 'Breakfast', cuisine: 'namerican', level: 'Easy', emoji: '🧁', title: 'Veggie Egg Muffins',
    time: 30, serves: 6, tags: ['high-protein', 'make-ahead', 'gluten-free', 'vegetarian'],
    blurb: 'Grab-and-go protein. Bake a tray, reheat all week.',
    kcal: 120, protein: 9,
    ingredients: [[8, '', 'eggs'], [0.25, 'cup', 'milk'], [1, '', 'bell pepper, diced'], [1, 'cup', 'baby spinach, chopped'],
      [0.5, 'cup', 'cherry tomatoes, quartered'], [0.33, 'cup', 'feta or cheddar, crumbled'], [null, '', 'salt and pepper']],
    steps: ['Heat the oven to 350°F (175°C) and grease a 12-cup muffin tin well.',
      'Divide the pepper, spinach, tomatoes and cheese between the cups.',
      'Whisk the eggs, milk, salt and pepper, then pour over the veg until each cup is about ¾ full.',
      'Bake 20 minutes until puffed and set in the middle.',
      'Cool 5 minutes before lifting out with a butter knife.'],
    tips: ['Fridge 4 days, freezer 2 months. Reheat 30–45 seconds in the microwave.', 'Serving = 2 muffins.'] },

  { id: 'avo-toast-egg', kind: 'human', course: 'Breakfast', cuisine: 'namerican', level: 'Easy', emoji: '🥑', title: 'Avocado Toast with Egg',
    time: 10, serves: 1, tags: ['vegetarian', 'quick'],
    blurb: 'Healthy fats, fibre and protein on a good slice of bread.',
    kcal: 380, protein: 15,
    ingredients: [[1, 'slice', 'whole-grain bread'], [0.5, '', 'ripe avocado'], [1, '', 'egg'], [1, 'tsp', 'lemon juice'],
      [null, '', 'chili flakes, salt, pepper'], [null, '', 'handful of rocket or microgreens (optional)']],
    steps: ['Toast the bread.',
      'Bring a small pan of water to a gentle simmer and poach the egg for 3 minutes (or fry it).',
      'Mash the avocado with lemon juice, salt and pepper and spread on the toast.',
      'Top with the egg, greens and chili flakes.'],
    tips: ['Add smoked salmon or a few chickpeas for extra protein.'] },

  { id: 'banana-pancakes', kind: 'human', course: 'Breakfast', cuisine: 'namerican', level: 'Easy', emoji: '🥞', title: 'Banana Oat Pancakes',
    time: 15, serves: 2, tags: ['vegetarian', 'gluten-free', 'no added sugar'],
    blurb: 'Blender batter: oats, banana, eggs. No flour, no sugar.',
    kcal: 310, protein: 12,
    ingredients: [[1, 'cup', 'rolled oats (certified GF if needed)'], [2, '', 'ripe bananas'], [2, '', 'eggs'],
      [1, 'tsp', 'baking powder'], [0.5, 'tsp', 'cinnamon'], [null, '', 'oil for the pan'], [null, '', 'berries and yogurt to serve']],
    steps: ['Blend everything except the oil until smooth. Let it sit 5 minutes to thicken.',
      'Heat a non-stick pan over medium-low and brush with oil.',
      'Pour ¼-cup rounds and cook 2–3 minutes until bubbles appear, then flip and cook 1–2 minutes more.',
      'Serve with berries and a spoon of yogurt.'],
    tips: ['Lower heat than normal pancakes — the banana browns fast.'] },

  { id: 'green-smoothie', kind: 'human', course: 'Drink', cuisine: 'namerican', level: 'Easy', emoji: '🥤', title: 'Green Protein Smoothie',
    time: 5, serves: 1, tags: ['vegetarian', 'quick', 'gluten-free', 'high-protein'],
    blurb: 'Tastes like banana and peanut butter. The spinach hides.',
    kcal: 350, protein: 22,
    ingredients: [[1, '', 'frozen banana'], [1, 'cup', 'baby spinach'], [0.75, 'cup', 'milk or soy milk'],
      [0.5, 'cup', 'plain Greek yogurt'], [1, 'tbsp', 'peanut butter'], [1, 'tbsp', 'ground flax (optional)']],
    steps: ['Put the liquid in the blender first, then everything else.',
      'Blend 45–60 seconds until completely smooth. Add ice or more milk to adjust.'],
    tips: ['Peel and freeze ripe bananas in halves so you always have smoothie bananas.'] },

  /* ───────────── Human: lunch ───────────── */
  { id: 'chickpea-salad', kind: 'human', course: 'Soup & Salad', cuisine: 'greek', level: 'Easy', emoji: '🥗', title: 'Mediterranean Chickpea Salad',
    time: 15, serves: 4, tags: ['vegan', 'gluten-free', 'make-ahead', 'no-cook'],
    blurb: 'Crunchy, lemony and better on day two.',
    kcal: 320, protein: 11,
    ingredients: [[2, 'cans', 'chickpeas (15 oz), drained and rinsed'], [1, '', 'English cucumber, diced'],
      [1, 'cup', 'cherry tomatoes, halved'], [0.5, '', 'red onion, finely diced'], [0.5, 'cup', 'kalamata olives, halved'],
      [0.25, 'cup', 'parsley, chopped'], [3, 'tbsp', 'olive oil'], [2, 'tbsp', 'lemon juice'], [1, 'tsp', 'dried oregano'],
      [null, '', 'salt and pepper'], [0.5, 'cup', 'feta (optional, not vegan)']],
    steps: ['Whisk the olive oil, lemon juice, oregano, salt and pepper in a big bowl.',
      'Add everything else and toss well.',
      'Taste, adjust salt and lemon, and let it sit 10 minutes before eating.'],
    tips: ['Keeps 4 days in the fridge. Add the feta just before serving.'] },

  { id: 'lentil-soup', kind: 'human', course: 'Soup & Salad', cuisine: 'mideast', level: 'Easy', emoji: '🍲', title: 'Red Lentil & Carrot Soup',
    time: 35, serves: 4, tags: ['vegan', 'gluten-free', 'make-ahead', 'budget'],
    blurb: 'Pantry staples, one pot, very filling.',
    kcal: 290, protein: 15,
    ingredients: [[1, 'tbsp', 'olive oil'], [1, '', 'onion, diced'], [3, '', 'carrots, diced'], [3, 'cloves', 'garlic, minced'],
      [2, 'tsp', 'ground cumin'], [1, 'tsp', 'smoked paprika'], [1, 'cup', 'red lentils, rinsed'], [1, 'can', 'diced tomatoes (14 oz)'],
      [5, 'cups', 'vegetable broth'], [1, '', 'lemon'], [null, '', 'salt and pepper']],
    steps: ['Warm the oil in a large pot over medium. Cook the onion and carrot 6 minutes until soft.',
      'Add garlic, cumin and paprika and stir 1 minute until fragrant.',
      'Add the lentils, tomatoes and broth. Bring to a boil, then simmer 20 minutes until the lentils fall apart.',
      'Blend half the soup (or all of it) for a creamy texture.',
      'Squeeze in the lemon, season, and serve.'],
    tips: ['Freezes well for 3 months.', 'Stir in a handful of spinach at the end for greens.'] },

  { id: 'quinoa-bowl', kind: 'human', course: 'Main', cuisine: 'namerican', level: 'Easy', emoji: '🥙', title: 'Rainbow Quinoa Bowl',
    time: 25, serves: 2, tags: ['vegan', 'gluten-free', 'make-ahead'],
    blurb: 'Quinoa, roasted chickpeas, crunchy veg and a tahini drizzle.',
    kcal: 520, protein: 19,
    ingredients: [[0.75, 'cup', 'quinoa, rinsed'], [1, 'can', 'chickpeas, drained'], [1, 'tsp', 'smoked paprika'],
      [1, 'tbsp', 'olive oil'], [1, 'cup', 'red cabbage, shredded'], [1, '', 'carrot, grated'], [0.5, '', 'avocado, sliced'],
      [2, 'tbsp', 'tahini'], [1, 'tbsp', 'lemon juice'], [1, 'tsp', 'maple syrup'], [null, '', 'water to thin, salt']],
    steps: ['Simmer the quinoa in 1½ cups water, covered, 15 minutes. Rest 5 minutes and fluff.',
      'Meanwhile, pat the chickpeas dry, toss with oil, paprika and salt, and pan-fry 8 minutes until crisp.',
      'Whisk tahini, lemon, maple and a pinch of salt; add water a spoon at a time until drizzly.',
      'Build bowls: quinoa, cabbage, carrot, chickpeas, avocado. Drizzle with the sauce.'],
    tips: ['Prep quinoa and sauce ahead; assemble in 3 minutes on busy days.'] },

  { id: 'lettuce-wraps', kind: 'human', course: 'Main', cuisine: 'chinese', level: 'Easy', emoji: '🥬', title: 'Turkey Lettuce Wraps',
    time: 20, serves: 3, tags: ['high-protein', 'low-carb', 'quick'],
    blurb: 'Sweet-salty ground turkey in crisp lettuce cups.',
    kcal: 280, protein: 27,
    ingredients: [[1, 'lb', 'lean ground turkey'], [1, 'tbsp', 'sesame oil'], [3, 'cloves', 'garlic, minced'],
      [1, 'tbsp', 'fresh ginger, grated'], [1, 'can', 'water chestnuts (8 oz), chopped'], [3, 'tbsp', 'low-sodium soy sauce'],
      [1, 'tbsp', 'rice vinegar'], [1, 'tsp', 'sriracha'], [3, '', 'green onions, sliced'], [1, 'head', 'butter lettuce']],
    steps: ['Heat the sesame oil in a large skillet over medium-high. Brown the turkey, breaking it up, about 6 minutes.',
      'Add garlic and ginger and cook 1 minute.',
      'Stir in the water chestnuts, soy sauce, vinegar and sriracha; cook 2 minutes until glossy.',
      'Spoon into lettuce leaves and top with green onions.'],
    tips: ['Use tamari instead of soy sauce to make it gluten-free.'] },

  { id: 'tuna-bean-salad', kind: 'human', course: 'Soup & Salad', cuisine: 'italian', level: 'Easy', emoji: '🐟', title: 'Tuna & White Bean Salad',
    time: 10, serves: 2, tags: ['high-protein', 'no-cook', 'quick', 'gluten-free'],
    blurb: 'Pantry lunch in ten minutes. No mayo.',
    kcal: 360, protein: 32,
    ingredients: [[1, 'can', 'tuna in water (5 oz), drained'], [1, 'can', 'white beans, drained and rinsed'],
      [0.25, '', 'red onion, thinly sliced'], [1, 'cup', 'cherry tomatoes, halved'], [2, 'tbsp', 'olive oil'],
      [1, 'tbsp', 'apple cider vinegar'], [1, 'tsp', 'Dijon mustard'], [2, 'cups', 'rocket or mixed greens'], [null, '', 'salt and pepper']],
    steps: ['Whisk oil, vinegar, Dijon, salt and pepper.',
      'Toss the beans, onion and tomatoes in the dressing, then gently fold in the tuna in chunks.',
      'Serve over the greens.'],
    tips: ['Soak the sliced onion in cold water 5 minutes to soften its bite.'] },

  /* ───────────── Human: dinner ───────────── */
  { id: 'sheet-salmon', kind: 'human', course: 'Main', cuisine: 'namerican', level: 'Easy', emoji: '🍣', title: 'Sheet-Pan Salmon & Veg',
    time: 30, serves: 4, tags: ['high-protein', 'gluten-free', 'one-pan'],
    blurb: 'Lemon-garlic salmon and roasted vegetables on one tray.',
    kcal: 430, protein: 34,
    ingredients: [[4, '', 'salmon fillets (5 oz each)'], [1, 'lb', 'baby potatoes, halved'], [1, 'bunch', 'asparagus or green beans'],
      [1, '', 'red bell pepper, sliced'], [3, 'tbsp', 'olive oil'], [3, 'cloves', 'garlic, minced'], [1, '', 'lemon'],
      [1, 'tsp', 'dried dill or Italian herbs'], [null, '', 'salt and pepper']],
    steps: ['Heat the oven to 425°F (220°C). Toss the potatoes with 1 tbsp oil and salt and roast 15 minutes.',
      'Mix the remaining oil with garlic, lemon zest, herbs, salt and pepper.',
      'Push the potatoes aside, add the asparagus and pepper, and lay the salmon in the middle. Brush the salmon and veg with the garlic oil.',
      'Roast 12 minutes until the salmon flakes easily.',
      'Squeeze lemon juice over everything and serve.'],
    tips: ['Salmon is done at 125–130°F in the thickest part for moist, or 145°F well-done.'] },

  { id: 'chicken-stirfry', kind: 'human', course: 'Main', cuisine: 'chinese', level: 'Medium', emoji: '🥢', title: 'Chicken & Veg Stir-Fry',
    time: 25, serves: 4, tags: ['high-protein', 'quick'],
    blurb: 'Faster than takeout, and you choose how much sauce.',
    kcal: 410, protein: 33,
    ingredients: [[1.25, 'lb', 'chicken breast, thinly sliced'], [1, 'tbsp', 'cornstarch'], [2, 'tbsp', 'neutral oil'],
      [1, 'head', 'broccoli, in florets'], [1, '', 'red bell pepper, sliced'], [1, 'cup', 'snap peas'], [3, 'cloves', 'garlic, minced'],
      [1, 'tbsp', 'ginger, grated'], [3, 'tbsp', 'low-sodium soy sauce'], [1, 'tbsp', 'honey'], [1, 'tbsp', 'rice vinegar'],
      [1, 'tsp', 'sesame oil'], [2, 'cups', 'cooked brown rice, to serve']],
    steps: ['Toss the chicken with cornstarch and a pinch of salt.',
      'Whisk soy sauce, honey, vinegar, sesame oil and 3 tbsp water for the sauce.',
      'Heat 1 tbsp oil in a wok or big skillet over high. Cook the chicken 5 minutes until browned and cooked through; set aside.',
      'Add the rest of the oil, then the broccoli and 2 tbsp water. Cover 2 minutes, then add the pepper and snap peas and stir-fry 2 minutes.',
      'Add garlic and ginger for 30 seconds, return the chicken, pour in the sauce and toss 1 minute until glossy.',
      'Serve over brown rice.'],
    tips: ['Cut everything before you turn on the heat — stir-fry moves fast.'] },

  { id: 'turkey-chili', kind: 'human', course: 'Main', cuisine: 'mexican', level: 'Easy', emoji: '🌶️', title: 'Turkey & Bean Chili',
    time: 45, serves: 6, tags: ['high-protein', 'gluten-free', 'make-ahead', 'freezer'],
    blurb: 'Big pot, lots of fibre, even better the next day.',
    kcal: 380, protein: 31,
    ingredients: [[1, 'tbsp', 'olive oil'], [1, 'lb', 'lean ground turkey'], [1, '', 'onion, diced'], [1, '', 'bell pepper, diced'],
      [3, 'cloves', 'garlic, minced'], [2, 'tbsp', 'chili powder'], [1, 'tsp', 'ground cumin'], [1, 'tsp', 'smoked paprika'],
      [1, 'can', 'crushed tomatoes (28 oz)'], [2, 'cans', 'beans (kidney/black), drained'], [1, 'cup', 'corn kernels'],
      [1, 'cup', 'broth or water'], [null, '', 'salt'], [null, '', 'toppings: yogurt, cilantro, avocado']],
    steps: ['Heat the oil in a large pot over medium-high. Brown the turkey with the onion and pepper, about 8 minutes.',
      'Stir in garlic, chili powder, cumin and paprika for 1 minute.',
      'Add tomatoes, beans, corn and broth. Bring to a boil, then simmer uncovered 25 minutes, stirring now and then.',
      'Season with salt and serve with Greek yogurt instead of sour cream.'],
    tips: ['Freeze in portions for up to 3 months.'] },

  { id: 'shrimp-tacos', kind: 'human', course: 'Main', cuisine: 'mexican', level: 'Easy', emoji: '🌮', title: 'Shrimp Tacos with Lime Slaw',
    time: 20, serves: 4, tags: ['high-protein', 'quick'],
    blurb: 'Spiced shrimp, crunchy slaw, creamy yogurt-lime sauce.',
    kcal: 390, protein: 28,
    ingredients: [[1, 'lb', 'shrimp, peeled and deveined'], [1, 'tsp', 'chili powder'], [1, 'tsp', 'cumin'], [0.5, 'tsp', 'garlic powder'],
      [1, 'tbsp', 'olive oil'], [3, 'cups', 'cabbage slaw mix'], [2, '', 'limes'], [0.5, 'cup', 'plain Greek yogurt'],
      [0.25, 'cup', 'cilantro, chopped'], [8, '', 'small corn tortillas'], [null, '', 'salt']],
    steps: ['Toss the slaw with the juice of 1 lime, cilantro and a pinch of salt.',
      'Mix the yogurt with the juice of half a lime and a pinch of salt for the sauce.',
      'Toss the shrimp with spices and salt. Cook in the oil over medium-high, 2 minutes per side, until pink.',
      'Warm the tortillas in a dry pan, 30 seconds a side.',
      'Fill with slaw and shrimp, drizzle with sauce, and serve with lime wedges.'],
    tips: ['Corn tortillas keep it gluten-free.'] },

  { id: 'chickpea-curry', kind: 'human', course: 'Main', cuisine: 'indian', level: 'Easy', emoji: '🍛', title: 'Chickpea & Spinach Curry',
    time: 30, serves: 4, tags: ['vegan', 'gluten-free', 'budget', 'freezer'],
    blurb: 'Creamy coconut curry from cans in your pantry.',
    kcal: 420, protein: 13,
    ingredients: [[1, 'tbsp', 'oil'], [1, '', 'onion, diced'], [3, 'cloves', 'garlic, minced'], [1, 'tbsp', 'ginger, grated'],
      [2, 'tbsp', 'curry powder'], [1, 'tsp', 'garam masala'], [1, 'can', 'diced tomatoes (14 oz)'], [1, 'can', 'light coconut milk (14 oz)'],
      [2, 'cans', 'chickpeas, drained'], [4, 'cups', 'baby spinach'], [1, '', 'lime'], [null, '', 'salt'], [null, '', 'rice or naan to serve']],
    steps: ['Soften the onion in the oil over medium, 6 minutes.',
      'Add garlic, ginger, curry powder and garam masala; stir 1 minute.',
      'Add tomatoes, coconut milk and chickpeas. Simmer 15 minutes until thickened.',
      'Stir in the spinach until wilted, add lime juice and salt to taste.'],
    tips: ['Add cubed sweet potato with the tomatoes for a heartier curry (simmer 20 minutes).'] },

  { id: 'lentil-bolognese', kind: 'human', course: 'Main', cuisine: 'italian', level: 'Medium', emoji: '🍝', title: 'Lentil Bolognese',
    time: 40, serves: 4, tags: ['vegan', 'budget', 'freezer'],
    blurb: 'Rich, meaty-tasting sauce made with lentils and mushrooms.',
    kcal: 480, protein: 22,
    ingredients: [[2, 'tbsp', 'olive oil'], [1, '', 'onion, finely diced'], [1, '', 'carrot, finely diced'], [1, 'stalk', 'celery, finely diced'],
      [8, 'oz', 'mushrooms, finely chopped'], [3, 'cloves', 'garlic'], [2, 'tbsp', 'tomato paste'], [0.75, 'cup', 'brown or green lentils, rinsed'],
      [1, 'can', 'crushed tomatoes (28 oz)'], [2, 'cups', 'vegetable broth'], [1, 'tsp', 'dried oregano'], [8, 'oz', 'whole-wheat spaghetti'],
      [null, '', 'salt, pepper, basil']],
    steps: ['Cook onion, carrot, celery and mushrooms in the oil over medium 10 minutes until the mushrooms brown.',
      'Add garlic and tomato paste; stir 2 minutes.',
      'Add lentils, tomatoes, broth and oregano. Simmer partly covered 25 minutes until the lentils are tender, stirring now and then.',
      'Meanwhile cook the spaghetti according to the packet.',
      'Season the sauce and serve over the pasta with basil.'],
    tips: ['Chop the mushrooms very small — that is what gives the "meaty" texture.'] },

  { id: 'greek-chicken', kind: 'human', course: 'Main', cuisine: 'greek', level: 'Easy', emoji: '🍗', title: 'Greek Chicken Sheet Pan',
    time: 40, serves: 4, tags: ['high-protein', 'gluten-free', 'one-pan'],
    blurb: 'Lemon-oregano chicken thighs with potatoes, peppers and tzatziki.',
    kcal: 460, protein: 35,
    ingredients: [[1.5, 'lb', 'boneless skinless chicken thighs'], [1, 'lb', 'baby potatoes, quartered'], [1, '', 'red onion, wedges'],
      [2, '', 'bell peppers, chunks'], [3, 'tbsp', 'olive oil'], [1, '', 'lemon'], [2, 'tsp', 'dried oregano'], [3, 'cloves', 'garlic'],
      [0.5, 'cup', 'tzatziki'], [null, '', 'salt and pepper']],
    steps: ['Heat the oven to 425°F (220°C).',
      'Whisk the oil, juice of the lemon, oregano, grated garlic, salt and pepper.',
      'Toss the chicken, potatoes, onion and peppers in the marinade and spread on a large tray in one layer.',
      'Roast 30 minutes, turning once, until the potatoes are golden and the chicken reaches 165°F (74°C).',
      'Serve with tzatziki.'],
    tips: ['Marinate the chicken in the morning for even more flavour.'] },

  { id: 'teriyaki-bowl', kind: 'human', course: 'Main', cuisine: 'japanese', level: 'Medium', emoji: '🍱', title: 'Teriyaki Tofu Rice Bowl',
    time: 30, serves: 3, tags: ['vegan', 'high-protein'],
    blurb: 'Crispy tofu, quick homemade teriyaki, edamame and rice.',
    kcal: 470, protein: 24,
    ingredients: [[1, 'block', 'extra-firm tofu (14 oz), pressed'], [1, 'tbsp', 'cornstarch'], [1, 'tbsp', 'oil'],
      [3, 'tbsp', 'low-sodium soy sauce'], [1, 'tbsp', 'maple syrup'], [1, 'tbsp', 'rice vinegar'], [1, 'tsp', 'ginger, grated'],
      [1, 'cup', 'shelled edamame'], [1, '', 'cucumber, sliced'], [1, '', 'carrot, ribboned'], [1.5, 'cups', 'cooked rice'], [null, '', 'sesame seeds']],
    steps: ['Cube the tofu, toss with cornstarch, and fry in the oil over medium-high 10 minutes, turning, until crisp.',
      'Whisk soy, maple, vinegar, ginger and 2 tbsp water. Pour over the tofu and toss 1 minute until sticky.',
      'Cook the edamame in boiling water 3 minutes.',
      'Build bowls: rice, tofu, edamame, cucumber, carrot. Sprinkle with sesame seeds.'],
    tips: ['Press tofu 15 minutes under a heavy pan wrapped in a towel — crispier result.'] },

  { id: 'black-bean-burgers', kind: 'human', course: 'Main', cuisine: 'namerican', level: 'Medium', emoji: '🍔', title: 'Black Bean Burgers',
    time: 35, serves: 4, tags: ['vegetarian', 'freezer', 'budget'],
    blurb: 'Smoky, crisp-edged patties that actually hold together.',
    kcal: 390, protein: 17,
    ingredients: [[2, 'cans', 'black beans, drained and patted dry'], [0.75, 'cup', 'rolled oats'], [1, '', 'egg'],
      [0.5, 'cup', 'cooked brown rice'], [1, 'tsp', 'smoked paprika'], [1, 'tsp', 'cumin'], [2, 'cloves', 'garlic'],
      [2, 'tbsp', 'BBQ sauce'], [1, 'tbsp', 'oil'], [4, '', 'whole-wheat buns'], [null, '', 'lettuce, tomato, onion']],
    steps: ['Spread the beans on a tray and bake at 350°F (175°C) for 10 minutes to dry them — the secret to firm patties.',
      'Pulse the oats into coarse flour in a food processor. Add the beans, egg, rice, spices, garlic and BBQ sauce and pulse until chunky (not smooth).',
      'Shape into 4 patties and chill 10 minutes.',
      'Pan-fry in the oil over medium 4–5 minutes a side until crisp.',
      'Serve on buns with the toppings.'],
    tips: ['Freeze shaped patties between parchment; cook from frozen, 6 minutes a side.'] },

  /* ───────────── Human: snacks ───────────── */
  { id: 'hummus', kind: 'human', course: 'Appetizer', cuisine: 'mideast', level: 'Easy', emoji: '🫘', title: 'Smooth Lemon Hummus',
    time: 10, serves: 6, tags: ['vegan', 'gluten-free', 'no-cook'],
    blurb: 'Silkier than store-bought, a fraction of the price.',
    kcal: 160, protein: 5,
    ingredients: [[1, 'can', 'chickpeas (keep the liquid)'], [0.25, 'cup', 'tahini'], [1, '', 'lemon, juiced'], [1, 'clove', 'garlic'],
      [2, 'tbsp', 'olive oil'], [0.5, 'tsp', 'cumin'], [3, 'tbsp', 'ice water or chickpea liquid'], [null, '', 'salt']],
    steps: ['Blend the tahini and lemon juice for 1 minute until whipped and pale.',
      'Add garlic, oil, cumin and salt and blend 30 seconds.',
      'Add the chickpeas and blend 2 minutes, adding the ice water a spoon at a time, until very smooth.',
      'Serve with carrot, cucumber and pepper sticks.'],
    tips: ['Keeps 5 days in the fridge.'] },

  { id: 'energy-bites', kind: 'human', course: 'Snack', cuisine: 'namerican', level: 'Easy', emoji: '🟤', title: 'No-Bake Energy Bites',
    time: 15, serves: 12, tags: ['vegetarian', 'no-cook', 'make-ahead'],
    blurb: 'Oats, nut butter and dark chocolate. One or two hits the spot.',
    kcal: 130, protein: 4,
    ingredients: [[1, 'cup', 'rolled oats'], [0.5, 'cup', 'peanut or almond butter'], [0.33, 'cup', 'honey'],
      [0.5, 'cup', 'ground flaxseed'], [0.33, 'cup', 'dark chocolate chips'], [1, 'tsp', 'vanilla']],
    steps: ['Stir everything together in a bowl until evenly mixed.',
      'Chill 20 minutes so it is easier to roll.',
      'Roll into 24 walnut-sized balls. Store in the fridge.'],
    tips: ['Serving = 2 bites. Fridge 1 week, freezer 3 months.', 'Not for the dog — chocolate is toxic to dogs.'] },

  { id: 'roast-chickpeas', kind: 'human', course: 'Snack', cuisine: 'namerican', level: 'Easy', emoji: '🥜', title: 'Crispy Roasted Chickpeas',
    time: 40, serves: 4, tags: ['vegan', 'gluten-free', 'budget'],
    blurb: 'A crunchy, salty snack with fibre and protein.',
    kcal: 150, protein: 6,
    ingredients: [[2, 'cans', 'chickpeas, drained'], [1, 'tbsp', 'olive oil'], [1, 'tsp', 'smoked paprika'], [0.5, 'tsp', 'garlic powder'], [0.5, 'tsp', 'salt']],
    steps: ['Heat the oven to 400°F (200°C). Dry the chickpeas very well with a towel and remove loose skins.',
      'Roast plain on a tray for 20 minutes.',
      'Toss with the oil and seasonings and roast 10–15 minutes more until crunchy.',
      'Cool on the tray — they crisp further as they cool.'],
    tips: ['Best eaten the same day; they soften overnight.'] },

  /* ───────────── Human: appetizers ───────────── */
  { id: 'chicken-satay', kind: 'human', course: 'Appetizer', cuisine: 'thai', level: 'Medium', emoji: '🍢', title: 'Chicken Satay with Peanut Sauce',
    time: 35, wait: '30 min marinating', serves: 4, tags: ['high-protein', 'gluten-free', 'party'],
    blurb: 'Turmeric-lime chicken skewers with a quick peanut dip.',
    kcal: 290, protein: 27,
    ingredients: [[1, 'lb', 'chicken breast, cut in long thin strips'], [0.5, 'cup', 'light coconut milk'], [1, 'tsp', 'ground turmeric'],
      [1, 'tsp', 'ground coriander'], [2, 'cloves', 'garlic, grated'], [1, 'tbsp', 'tamari or low-sodium soy sauce'], [1, '', 'lime'],
      [3, 'tbsp', 'natural peanut butter'], [1, 'tbsp', 'honey'], [1, 'tsp', 'sriracha'], [12, '', 'bamboo skewers, soaked 20 minutes']],
    steps: ['Mix half the coconut milk with turmeric, coriander, garlic, tamari and the zest of the lime. Toss the chicken in it and marinate 30 minutes.',
      'Whisk the peanut butter, the rest of the coconut milk, honey, sriracha and the lime juice. Thin with warm water until dippable.',
      'Thread the chicken onto the soaked skewers.',
      'Grill or broil on high 3–4 minutes a side until charred at the edges and cooked through.',
      'Serve with the peanut sauce and cucumber slices.'],
    tips: ['No grill? A grill pan or the oven broiler works well.'] },

  { id: 'spring-rolls', kind: 'human', course: 'Appetizer', cuisine: 'viet', level: 'Medium', emoji: '🥢', title: 'Shrimp Fresh Spring Rolls',
    time: 30, serves: 4, tags: ['gluten-free', 'no-oven', 'light'],
    blurb: 'Rice-paper rolls packed with herbs, crunchy veg and shrimp.',
    kcal: 210, protein: 14,
    ingredients: [[12, '', 'rice paper wrappers'], [12, '', 'cooked shrimp, halved lengthwise'], [2, 'oz', 'rice vermicelli'],
      [1, '', 'carrot, julienned'], [1, '', 'cucumber, julienned'], [1, 'cup', 'lettuce, shredded'], [0.5, 'cup', 'mint and cilantro leaves'],
      [3, 'tbsp', 'hoisin sauce'], [1, 'tbsp', 'peanut butter'], [1, 'tbsp', 'lime juice']],
    steps: ['Cook the vermicelli in boiling water 3 minutes, rinse cold and drain well.',
      'Set out all the fillings within reach — rolling goes fast once you start.',
      'Dip one rice paper in warm water for 5 seconds and lay it flat on a damp board.',
      'Lay 2 shrimp halves pink side down in the middle, then herbs, noodles and veg on top.',
      'Fold the sides in and roll up tightly like a burrito. Repeat.',
      'Stir the hoisin, peanut butter, lime and a splash of water for the dipping sauce.'],
    tips: ['Cover finished rolls with a damp towel so they do not dry out.', 'Use tofu strips to make them vegetarian.'] },

  { id: 'bruschetta', kind: 'human', course: 'Appetizer', cuisine: 'italian', level: 'Easy', emoji: '🍅', title: 'Tomato Basil Bruschetta',
    time: 15, serves: 6, tags: ['vegan', 'quick', 'party'],
    blurb: 'Ripe tomatoes, garlic and basil on crisp toasted bread.',
    kcal: 150, protein: 4,
    ingredients: [[1, '', 'whole-grain baguette, sliced on an angle'], [4, '', 'ripe Roma tomatoes, finely diced'], [0.25, 'cup', 'fresh basil, sliced'],
      [1, 'clove', 'garlic, halved, plus 1 minced'], [2, 'tbsp', 'olive oil'], [1, 'tsp', 'balsamic vinegar'], [null, '', 'salt and pepper']],
    steps: ['Toss the tomatoes, basil, minced garlic, 1 tbsp oil, balsamic, salt and pepper. Let it sit 10 minutes.',
      'Brush the bread with the remaining oil and toast under the broiler 1–2 minutes a side.',
      'Rub each warm toast with the cut garlic clove.',
      'Spoon the tomatoes on just before serving so the bread stays crisp.'],
    tips: ['Drain the tomato mix in a sieve if your tomatoes are very juicy.'] },

  { id: 'edamame', kind: 'human', course: 'Appetizer', cuisine: 'japanese', level: 'Easy', emoji: '🫛', title: 'Chili-Garlic Edamame',
    time: 10, serves: 4, tags: ['vegan', 'quick', 'high-protein'],
    blurb: 'Sticky, spicy, salty pods you eat with your fingers.',
    kcal: 140, protein: 11,
    ingredients: [[1, 'lb', 'frozen edamame in pods'], [1, 'tsp', 'sesame oil'], [3, 'cloves', 'garlic, minced'], [1, 'tbsp', 'low-sodium soy sauce'],
      [1, 'tsp', 'chili crisp or chili flakes'], [null, '', 'flaky salt']],
    steps: ['Boil the edamame 4 minutes and drain well.',
      'Warm the sesame oil in a skillet over medium, add garlic and cook 30 seconds.',
      'Add the edamame, soy sauce and chili and toss 1 minute until coated.',
      'Sprinkle with flaky salt and serve with a bowl for the empty pods.'],
    tips: ['Squeeze the beans out with your teeth — the pods are not eaten.'] },

  /* ───────────── Human: soups & salads ───────────── */
  { id: 'tabbouleh', kind: 'human', course: 'Soup & Salad', cuisine: 'mideast', level: 'Easy', emoji: '🌿', title: 'Lemony Tabbouleh',
    time: 25, serves: 4, tags: ['vegan', 'make-ahead'],
    blurb: 'A herb salad with a little bulgur, not the other way round.',
    kcal: 180, protein: 4,
    ingredients: [[0.33, 'cup', 'fine bulgur'], [2, 'bunches', 'flat-leaf parsley, finely chopped'], [0.5, 'cup', 'mint, finely chopped'],
      [3, '', 'tomatoes, finely diced'], [4, '', 'green onions, sliced'], [0.25, 'cup', 'olive oil'], [2, '', 'lemons, juiced'], [null, '', 'salt']],
    steps: ['Cover the bulgur with boiling water, cover and leave 15 minutes. Drain and squeeze dry.',
      'Meanwhile chop the herbs very finely with a sharp knife (a food processor bruises them).',
      'Mix everything with the oil, lemon juice and salt.',
      'Taste — it should be bright and lemony. Add more lemon if needed.'],
    tips: ['Use quinoa instead of bulgur to make it gluten-free.'] },

  { id: 'chicken-pho', kind: 'human', course: 'Soup & Salad', cuisine: 'viet', level: 'Hard', emoji: '🍜', title: 'Chicken Pho from Scratch',
    time: 40, wait: '1½ hours simmering', serves: 4, tags: ['high-protein', 'gluten-free', 'weekend project'],
    blurb: 'Charred onion and ginger, toasted spices and a clear, fragrant broth.',
    kcal: 450, protein: 35,
    ingredients: [[2.5, 'lb', 'bone-in chicken thighs and drumsticks'], [1, '', 'large onion, halved'], [1, 'piece', 'ginger (3 inch), halved lengthwise'],
      [3, '', 'star anise'], [1, '', 'cinnamon stick'], [4, '', 'cloves'], [1, 'tbsp', 'coriander seeds'], [12, 'cups', 'water'],
      [3, 'tbsp', 'fish sauce'], [1, 'tbsp', 'sugar'], [8, 'oz', 'flat rice noodles'],
      [null, '', 'to serve: bean sprouts, Thai basil, cilantro, lime, sliced chili, hoisin, sriracha']],
    steps: ['Char the onion and ginger cut side down in a dry pot over high heat, 5 minutes, until blackened in spots.',
      'Add the star anise, cinnamon, cloves and coriander and toast 1 minute until fragrant.',
      'Add the chicken and water. Bring to a boil, skim off the foam, then lower to the gentlest simmer.',
      'Simmer uncovered 30 minutes, lift out the chicken, shred the meat and return the bones to the pot.',
      'Simmer the broth 1 hour more. Strain, then season with fish sauce and sugar until it tastes deep and balanced.',
      'Soak or cook the noodles per the packet and divide into big bowls with the chicken.',
      'Ladle the boiling broth over and serve with the herbs, sprouts, lime and sauces at the table.'],
    tips: ['Never let it boil hard after skimming — that keeps the broth clear.', 'Broth freezes well for 3 months.'] },

  /* ───────────── Human: more mains ───────────── */
  { id: 'tikka-masala', kind: 'human', course: 'Main', cuisine: 'indian', level: 'Medium', emoji: '🍛', title: 'Lighter Chicken Tikka Masala',
    time: 45, wait: '30 min marinating', serves: 4, tags: ['high-protein', 'gluten-free'],
    blurb: 'Yogurt-marinated chicken in a creamy tomato sauce — no heavy cream.',
    kcal: 390, protein: 38,
    ingredients: [[1.5, 'lb', 'boneless skinless chicken thighs, cubed'], [0.75, 'cup', 'plain Greek yogurt, divided'], [2, 'tsp', 'garam masala, divided'],
      [1, 'tsp', 'ground turmeric'], [1, 'tsp', 'smoked paprika'], [1, 'tbsp', 'oil'], [1, '', 'onion, finely diced'], [4, 'cloves', 'garlic, minced'],
      [1, 'tbsp', 'ginger, grated'], [1, 'tsp', 'ground cumin'], [1, 'can', 'crushed tomatoes (28 oz)'], [0.5, 'cup', 'light coconut milk'],
      [null, '', 'salt, cilantro, brown rice to serve']],
    steps: ['Marinate the chicken in ½ cup yogurt, 1 tsp garam masala, turmeric, paprika and salt for 30 minutes (or overnight).',
      'Spread the chicken on a lined tray and broil 8 minutes until charred at the edges.',
      'Meanwhile soften the onion in the oil over medium, 8 minutes. Add garlic, ginger, cumin and the rest of the garam masala for 1 minute.',
      'Add the tomatoes and simmer 15 minutes until thick.',
      'Stir in the coconut milk and the chicken with its juices; simmer 5 minutes.',
      'Off the heat, swirl in the remaining yogurt, season and top with cilantro.'],
    tips: ['Adding yogurt off the heat stops it from splitting.'] },

  { id: 'tagine', kind: 'human', course: 'Main', cuisine: 'nafrican', level: 'Medium', emoji: '🫖', title: 'Moroccan Chicken & Chickpea Tagine',
    time: 55, serves: 4, tags: ['high-protein', 'gluten-free', 'one-pot'],
    blurb: 'Warm spices, apricots and olives in one fragrant pot.',
    kcal: 470, protein: 36,
    ingredients: [[1.5, 'lb', 'boneless skinless chicken thighs'], [1, 'tbsp', 'olive oil'], [1, '', 'onion, sliced'], [3, 'cloves', 'garlic'],
      [2, 'tsp', 'ground cumin'], [1, 'tsp', 'ground cinnamon'], [1, 'tsp', 'ground ginger'], [1, 'tsp', 'paprika'], [1, 'can', 'diced tomatoes (14 oz)'],
      [1, 'cup', 'chicken broth'], [1, 'can', 'chickpeas, drained'], [0.5, 'cup', 'dried apricots, halved'], [0.33, 'cup', 'green olives'],
      [1, '', 'lemon'], [null, '', 'cilantro and couscous or quinoa to serve']],
    steps: ['Season the chicken with salt and brown it in the oil in a heavy pot over medium-high, 4 minutes a side. Set aside.',
      'Lower the heat, add the onion and cook 6 minutes. Add garlic and all the spices for 1 minute.',
      'Add tomatoes, broth, chickpeas, apricots and the chicken. Cover and simmer 25 minutes.',
      'Add the olives and lemon zest and simmer 5 minutes uncovered to thicken.',
      'Squeeze in lemon juice, scatter with cilantro, and serve over couscous or quinoa.'],
    tips: ['Even better the next day.'] },

  { id: 'shawarma-bowl', kind: 'human', course: 'Main', cuisine: 'mideast', level: 'Medium', emoji: '🥙', title: 'Chicken Shawarma Bowls',
    time: 40, wait: '1 hour marinating', serves: 4, tags: ['high-protein', 'meal-prep'],
    blurb: 'Spiced roasted chicken, garlic yogurt sauce and crunchy salad.',
    kcal: 520, protein: 42,
    ingredients: [[1.5, 'lb', 'boneless skinless chicken thighs'], [3, 'tbsp', 'olive oil'], [1, '', 'lemon, juiced'], [4, 'cloves', 'garlic, minced, divided'],
      [2, 'tsp', 'ground cumin'], [2, 'tsp', 'paprika'], [1, 'tsp', 'ground coriander'], [0.5, 'tsp', 'cinnamon'], [0.5, 'tsp', 'turmeric'],
      [0.75, 'cup', 'plain Greek yogurt'], [2, 'cups', 'cooked brown rice or quinoa'], [1, '', 'cucumber, diced'], [2, '', 'tomatoes, diced'],
      [0.25, '', 'red onion, sliced'], [null, '', 'pickled turnips or pickles (optional), salt']],
    steps: ['Mix the oil, half the lemon juice, 3 cloves garlic, all the spices and salt. Coat the chicken and marinate at least 1 hour.',
      'Roast on a lined tray at 425°F (220°C) for 25 minutes, then broil 3 minutes to char.',
      'Stir the yogurt with the last garlic clove, the rest of the lemon juice and a pinch of salt.',
      'Rest the chicken 5 minutes and slice thinly.',
      'Build bowls: rice, chicken, cucumber, tomato, onion, pickles and a big spoon of garlic sauce.'],
    tips: ['Stuff it in whole-wheat pita for wraps instead.'] },

  { id: 'bibimbap', kind: 'human', course: 'Main', cuisine: 'korean', level: 'Hard', emoji: '🍚', title: 'Beef Bulgogi Bibimbap',
    time: 60, wait: '1 hour marinating', serves: 4, tags: ['high-protein', 'weekend project'],
    blurb: 'Sweet-savory beef, five seasoned vegetables and a runny egg over rice.',
    kcal: 580, protein: 34,
    ingredients: [[1, 'lb', 'lean beef sirloin, very thinly sliced'], [0.5, '', 'Asian pear, grated'], [3, 'tbsp', 'low-sodium soy sauce'],
      [1, 'tbsp', 'honey'], [3, 'cloves', 'garlic, minced'], [2, 'tsp', 'sesame oil, plus more'], [2, 'cups', 'spinach'], [1, 'cup', 'bean sprouts'],
      [1, '', 'carrot, julienned'], [1, '', 'zucchini, julienned'], [6, 'oz', 'shiitake mushrooms, sliced'], [4, '', 'eggs'],
      [3, 'cups', 'cooked short-grain rice'], [2, 'tbsp', 'gochujang'], [1, 'tsp', 'rice vinegar'], [null, '', 'sesame seeds, oil, salt']],
    steps: ['Mix the pear, soy sauce, honey, garlic and 2 tsp sesame oil. Marinate the beef 1 hour.',
      'Blanch the spinach 30 seconds and the sprouts 2 minutes. Squeeze dry and season each with a little sesame oil and salt.',
      'In a hot pan with a little oil, sauté the carrot, zucchini and mushrooms one at a time, 2 minutes each, seasoning each lightly.',
      'Turn the heat to high and sear the beef in batches, 2 minutes, until caramelised.',
      'Fry the eggs sunny side up.',
      'Stir the gochujang with the vinegar, 1 tsp sesame oil and a splash of water.',
      'Fill bowls with rice, arrange the vegetables and beef around the edge, top with an egg and sesame seeds. Mix everything with the sauce at the table.'],
    tips: ['Freezing the beef 30 minutes makes paper-thin slicing easy.', 'Some gochujang brands contain alcohol — check the label if you avoid it.'] },

  { id: 'joojeh-kabab', kind: 'human', course: 'Main', cuisine: 'persian', level: 'Hard', emoji: '🍢', title: 'Joojeh Kabab with Saffron Rice',
    time: 75, wait: '4 hours marinating', serves: 4, tags: ['high-protein', 'gluten-free', 'weekend project'],
    blurb: 'Saffron-lemon chicken kabobs with fluffy basmati and a crispy tahdig crust.',
    kcal: 560, protein: 40,
    ingredients: [[2, 'lb', 'boneless chicken thighs, in 1½-inch pieces'], [0.5, 'tsp', 'saffron threads'], [1, '', 'onion, grated'],
      [0.5, 'cup', 'plain yogurt'], [2, '', 'lemons, juiced'], [2, 'tbsp', 'olive oil'], [2, 'cups', 'basmati rice'], [2, 'tbsp', 'butter or oil'],
      [4, '', 'Roma tomatoes'], [null, '', 'salt, pepper, sumac']],
    steps: ['Grind the saffron with a pinch of sugar and steep in 4 tbsp hot water for 10 minutes.',
      'Mix the onion, yogurt, lemon juice, oil, half the saffron water, salt and pepper. Marinate the chicken at least 4 hours or overnight.',
      'Rinse the rice until the water runs clear, then boil in plenty of salted water 6 minutes until just soft outside. Drain.',
      'Heat the butter in a non-stick pot, spread a thin layer of rice over the bottom, then mound the rest on top. Poke a few holes with a spoon handle.',
      'Cover the lid with a towel, cook 10 minutes on medium, then 40 minutes on low to form the crispy tahdig.',
      'Thread the chicken and tomatoes on skewers and grill on high 12–15 minutes, turning, until charred and cooked through.',
      'Mix a cup of rice with the rest of the saffron water and scatter it over the top. Serve with the kabobs, grilled tomatoes, sumac and the tahdig broken into pieces.'],
    tips: ['Flip the pot onto a plate to show off the tahdig whole.', 'No grill: broil on a rack 6–7 minutes a side.'] },

  { id: 'shakshuka', kind: 'human', course: 'Breakfast', cuisine: 'nafrican', level: 'Easy', emoji: '🍳', title: 'Shakshuka',
    time: 30, serves: 3, tags: ['vegetarian', 'gluten-free', 'one-pan'],
    blurb: 'Eggs poached in a spiced pepper and tomato sauce.',
    kcal: 280, protein: 16,
    ingredients: [[1, 'tbsp', 'olive oil'], [1, '', 'onion, diced'], [1, '', 'red bell pepper, diced'], [3, 'cloves', 'garlic, sliced'],
      [1, 'tsp', 'ground cumin'], [1, 'tsp', 'smoked paprika'], [0.25, 'tsp', 'chili flakes'], [1, 'can', 'crushed tomatoes (28 oz)'],
      [6, '', 'eggs'], [0.25, 'cup', 'feta, crumbled'], [null, '', 'parsley, salt, whole-grain bread to serve']],
    steps: ['Cook the onion and pepper in the oil in a wide skillet over medium, 8 minutes.',
      'Add garlic and spices for 1 minute, then the tomatoes. Simmer 10 minutes until thick, and season.',
      'Make 6 wells and crack an egg into each. Cover and cook on low 6–8 minutes until the whites are set and the yolks still soft.',
      'Scatter with feta and parsley and serve straight from the pan with bread.'],
    tips: ['Leave out the feta to make it dairy-free.'] },

  /* ───────────── Human: sides ───────────── */
  { id: 'raita', kind: 'human', course: 'Side', cuisine: 'indian', level: 'Easy', emoji: '🥒', title: 'Cucumber Mint Raita',
    time: 10, serves: 4, tags: ['vegetarian', 'gluten-free', 'no-cook', 'quick'],
    blurb: 'Cool yogurt side that tames any curry.',
    kcal: 60, protein: 5,
    ingredients: [[1, 'cup', 'plain Greek yogurt'], [0.5, '', 'English cucumber, grated and squeezed'], [2, 'tbsp', 'mint, chopped'],
      [0.5, 'tsp', 'ground cumin (toasted if you can)'], [null, '', 'salt']],
    steps: ['Squeeze the grated cucumber in a towel to remove the water.', 'Stir everything together and chill until serving.'],
    tips: ['Toast the cumin in a dry pan 30 seconds for a smokier flavour.'] },

  { id: 'street-corn', kind: 'human', course: 'Side', cuisine: 'mexican', level: 'Easy', emoji: '🌽', title: 'Street Corn Salad',
    time: 15, serves: 4, tags: ['vegetarian', 'gluten-free', 'quick'],
    blurb: 'Charred corn, lime, chili and cotija — elote in a bowl.',
    kcal: 170, protein: 6,
    ingredients: [[3, 'cups', 'corn kernels (frozen is fine)'], [1, 'tsp', 'oil'], [3, 'tbsp', 'plain Greek yogurt'], [1, '', 'lime'],
      [0.5, 'tsp', 'chili powder'], [0.25, 'cup', 'cotija or feta, crumbled'], [2, 'tbsp', 'cilantro, chopped'], [0.25, '', 'red onion, minced']],
    steps: ['Heat the oil in a skillet over high. Cook the corn without stirring 3 minutes to char, then stir and char 3 minutes more.',
      'Mix the yogurt, lime juice and chili powder.',
      'Toss the warm corn with the sauce, onion, cheese and cilantro.'],
    tips: ['Great with the shrimp tacos or turkey chili.'] },

  { id: 'roast-broccoli', kind: 'human', course: 'Side', cuisine: 'namerican', level: 'Easy', emoji: '🥦', title: 'Garlic Parmesan Roasted Broccoli',
    time: 25, serves: 4, tags: ['vegetarian', 'gluten-free'],
    blurb: 'Crispy-edged broccoli people actually fight over.',
    kcal: 110, protein: 6,
    ingredients: [[2, 'heads', 'broccoli, in florets'], [2, 'tbsp', 'olive oil'], [3, 'cloves', 'garlic, sliced'], [2, 'tbsp', 'grated parmesan'],
      [0.5, '', 'lemon'], [null, '', 'salt, pepper, chili flakes']],
    steps: ['Heat the oven to 425°F (220°C).',
      'Toss the broccoli with the oil, salt and pepper and spread out on a tray — crowding makes it steam.',
      'Roast 15 minutes, add the garlic, toss and roast 5 minutes more.',
      'Finish with parmesan, a squeeze of lemon and chili flakes.'],
    tips: ['Most parmesan uses animal rennet; look for a vegetarian hard cheese if that matters to you.'] },

  /* ───────────── Human: desserts ───────────── */
  { id: 'mango-chia', kind: 'human', course: 'Dessert', cuisine: 'thai', level: 'Easy', emoji: '🥭', title: 'Mango Coconut Chia Pudding',
    time: 10, wait: '4 hours chilling', serves: 4, tags: ['vegan', 'gluten-free', 'make-ahead'],
    blurb: 'Tastes like mango sticky rice, with fibre instead of sugar.',
    kcal: 210, protein: 5,
    ingredients: [[1, 'can', 'light coconut milk (14 oz)'], [0.33, 'cup', 'chia seeds'], [1, 'tbsp', 'maple syrup'], [1, 'pinch', 'salt'],
      [2, '', 'ripe mangoes, diced'], [1, 'tbsp', 'toasted coconut flakes'], [1, '', 'lime']],
    steps: ['Whisk the coconut milk, chia, maple syrup and salt. Wait 5 minutes and whisk again to stop clumps.',
      'Chill at least 4 hours or overnight.',
      'Blend half the mango with a squeeze of lime into a purée.',
      'Layer pudding, purée and diced mango in glasses and top with coconut.'],
    tips: ['Keeps 4 days in the fridge.'] },

  { id: 'baked-apples', kind: 'human', course: 'Dessert', cuisine: 'namerican', level: 'Easy', emoji: '🍎', title: 'Maple Cinnamon Baked Apples',
    time: 45, serves: 4, tags: ['vegetarian', 'gluten-free'],
    blurb: 'Like apple crumble, minus most of the sugar and butter.',
    kcal: 220, protein: 3,
    ingredients: [[4, '', 'firm apples (Honeycrisp, Gala)'], [0.5, 'cup', 'rolled oats'], [0.25, 'cup', 'chopped walnuts or pecans'],
      [2, 'tbsp', 'maple syrup'], [1, 'tbsp', 'butter or coconut oil, melted'], [1, 'tsp', 'cinnamon'], [0.5, 'cup', 'water'],
      [null, '', 'plain Greek yogurt to serve']],
    steps: ['Heat the oven to 350°F (175°C).',
      'Core the apples with a small knife or melon baller, leaving the bottom intact.',
      'Mix the oats, nuts, maple, butter and cinnamon and pack it into the apples.',
      'Stand them in a small dish with the water and bake 35 minutes until tender.',
      'Spoon the juices over and serve with yogurt.'],
    tips: ['Use certified gluten-free oats if needed.'] },

  { id: 'choc-mousse', kind: 'human', course: 'Dessert', cuisine: 'namerican', level: 'Easy', emoji: '🍫', title: 'Chocolate Avocado Mousse',
    time: 10, wait: '1 hour chilling', serves: 4, tags: ['vegan', 'gluten-free', 'no-cook'],
    blurb: 'Silky, rich and secretly made with avocado.',
    kcal: 230, protein: 4,
    ingredients: [[2, '', 'ripe avocados'], [0.33, 'cup', 'unsweetened cocoa powder'], [0.25, 'cup', 'maple syrup'], [0.25, 'cup', 'milk of choice'],
      [1, 'pinch', 'salt'], [null, '', 'raspberries to serve']],
    steps: ['Blend everything until completely smooth, scraping down the sides.', 'Taste and add more maple if you like it sweeter.', 'Chill 1 hour and top with raspberries.'],
    tips: ['Very ripe avocados = no avocado taste.', 'Not for the dog — avocado and chocolate are both on the no list.'] },

  { id: 'yogurt-bark', kind: 'human', course: 'Dessert', cuisine: 'greek', level: 'Easy', emoji: '🍓', title: 'Frozen Greek Yogurt Bark',
    time: 10, wait: '3 hours freezing', serves: 6, tags: ['vegetarian', 'gluten-free', 'high-protein'],
    blurb: 'Snap-able frozen yogurt with berries and pistachios.',
    kcal: 120, protein: 9,
    ingredients: [[2, 'cups', 'plain Greek yogurt'], [2, 'tbsp', 'honey'], [1, 'cup', 'mixed berries'], [2, 'tbsp', 'pistachios, chopped']],
    steps: ['Stir the honey into the yogurt and spread ½ inch thick on a parchment-lined tray.',
      'Scatter with berries and pistachios and press them in lightly.',
      'Freeze 3 hours, then break into pieces.'],
    tips: ['Store in a freezer bag. Let it sit 2 minutes before eating.'] },

  /* ───────────── Dog ───────────── */
  { id: 'dog-pumpkin-biscuits', kind: 'dog', course: 'Treat', level: 'Easy', emoji: '🦴', title: 'Pumpkin Peanut Butter Biscuits',
    time: 45, serves: 40, servesUnit: 'biscuits', tags: ['treat', 'baked', 'freezer'],
    blurb: 'Crunchy training-size biscuits with four ingredients.',
    kcal: 25, kcalUnit: 'biscuit',
    ingredients: [[2.5, 'cups', 'whole-wheat or oat flour'], [0.5, 'cup', 'plain canned pumpkin (NOT pie filling)'], [2, '', 'eggs'],
      [3, 'tbsp', 'xylitol-free peanut butter'], [null, '', 'water as needed']],
    steps: ['Heat the oven to 350°F (175°C) and line a tray with parchment.',
      'Mix the pumpkin, eggs and peanut butter, then stir in the flour. Add water a spoon at a time until it forms a stiff dough.',
      'Roll to ¼ inch thick and cut into small shapes (about 1 inch).',
      'Bake 35 minutes, then turn off the oven and leave them inside to dry and harden as it cools.'],
    tips: ['Fridge 2 weeks, freezer 3 months.', 'Check the peanut butter label for xylitol (also called birch sugar) — it is deadly for dogs.'] },

  { id: 'dog-bland-diet', kind: 'dog', course: 'Meal', level: 'Easy', emoji: '🍚', title: 'Chicken & Rice (Upset Tummy)',
    time: 30, serves: 4, servesUnit: 'small meals', tags: ['bland', 'short-term'],
    blurb: 'The classic bland meal vets suggest for a day or two of tummy trouble.',
    ingredients: [[1, 'lb', 'boneless skinless chicken breast'], [1, 'cup', 'white rice (not brown)'], [null, '', 'water — no salt, oil or seasoning']],
    steps: ['Cover the chicken with water in a pot, bring to a boil, then simmer 15–20 minutes until fully cooked.',
      'Lift out the chicken and cook the rice in that broth until very soft.',
      'Shred the chicken finely and remove any fat.',
      'Mix about 1 part chicken to 2 parts rice. Cool completely before serving.',
      'Feed small meals 3–4 times a day, then mix back into the regular food over 2–3 days.'],
    tips: ['Short-term only — it is not a complete diet.', 'Call your vet if vomiting or diarrhea lasts more than a day, there is blood, or your dog is lethargic. Puppies dehydrate quickly.'] },

  { id: 'dog-pupsicles', kind: 'dog', course: 'Treat', level: 'Easy', emoji: '🧊', title: 'Banana Yogurt Pupsicles',
    time: 10, wait: '3 hours freezing', serves: 20, servesUnit: 'cubes', tags: ['treat', 'frozen', 'no-cook', 'teething'],
    blurb: 'Cooling frozen cubes — great for teething puppies and hot days.',
    kcal: 15, kcalUnit: 'cube',
    ingredients: [[1, 'cup', 'plain unsweetened yogurt (no xylitol)'], [1, '', 'ripe banana'], [2, 'tbsp', 'xylitol-free peanut butter']],
    steps: ['Blend or mash everything until smooth.',
      'Spoon into a silicone ice-cube tray or small moulds.',
      'Freeze at least 3 hours. Pop out and serve one at a time outside or on a mat.'],
    tips: ['Some dogs are lactose-sensitive — start with one cube.', 'Swap banana for blueberries or plain pumpkin.'] },

  { id: 'dog-sweet-potato-chews', kind: 'dog', course: 'Treat', level: 'Easy', emoji: '🍠', title: 'Sweet Potato Chews',
    time: 15, wait: '3 hours baking', serves: 30, servesUnit: 'chews', tags: ['treat', 'single-ingredient', 'baked'],
    blurb: 'One ingredient, slow-baked until leathery and chewy.',
    kcal: 10, kcalUnit: 'chew',
    ingredients: [[2, '', 'large sweet potatoes, washed']],
    steps: ['Heat the oven to 250°F (120°C) and line two trays with parchment.',
      'Slice the sweet potatoes lengthwise about ⅓ inch thick.',
      'Lay flat without overlapping and bake 2½–3 hours, flipping halfway, until dry and leathery but still bendy.',
      'Cool completely on a rack.'],
    tips: ['Fridge 2 weeks. Thinner slices = crunchier, thicker = chewier.', 'Supervise chewing and take it away when it gets small enough to swallow whole.'] },

  { id: 'dog-turkey-topper', kind: 'dog', course: 'Topper', level: 'Easy', emoji: '🥕', title: 'Turkey & Veggie Meal Topper',
    time: 25, serves: 14, servesUnit: '¼-cup portions', tags: ['topper', 'freezer'],
    blurb: 'A spoonful on top of kibble makes dinner exciting. Not a complete diet on its own.',
    kcal: 55, kcalUnit: '¼ cup',
    ingredients: [[1, 'lb', 'lean ground turkey'], [1, 'cup', 'carrots, finely grated'], [1, 'cup', 'green beans, chopped small'],
      [0.5, 'cup', 'plain canned pumpkin'], [0.5, 'cup', 'cooked brown rice'], [1, 'cup', 'water']],
    steps: ['Brown the turkey in a dry non-stick pan over medium, breaking it into small pieces. Drain the fat.',
      'Add carrots, green beans and water. Simmer 10 minutes until the veg is soft.',
      'Stir in the pumpkin and rice. Cool completely.',
      'Portion into ¼-cup servings in an ice-cube tray or bags.'],
    tips: ['Fridge 3 days, freezer 2 months.', 'Reduce the kibble a little so total daily calories stay the same.', 'No onion, garlic, salt or seasoning — ever.'] },

  { id: 'dog-salmon-cakes', kind: 'dog', course: 'Treat', level: 'Medium', emoji: '🐟', title: 'Salmon & Sweet Potato Bites',
    time: 35, serves: 30, servesUnit: 'bites', tags: ['treat', 'baked', 'omega-3'],
    blurb: 'Soft, fishy bites dogs go wild for. Good high-value training rewards.',
    kcal: 20, kcalUnit: 'bite',
    ingredients: [[1, 'can', 'salmon in water, no salt added (6 oz), drained'], [1, 'cup', 'mashed cooked sweet potato'],
      [1, '', 'egg'], [0.5, 'cup', 'oat flour']],
    steps: ['Heat the oven to 350°F (175°C) and line a tray.',
      'Mash the salmon (soft canned bones mash in fine) with the sweet potato and egg, then stir in the oat flour.',
      'Roll into small balls (about a teaspoon) and flatten slightly.',
      'Bake 20 minutes until firm. Cool completely.'],
    tips: ['Fridge 5 days, freezer 2 months. Break in half for training.', 'Never feed raw salmon — it can carry a parasite that is dangerous to dogs.'] },

  { id: 'dog-blueberry-carrot', kind: 'dog', course: 'Treat', level: 'Easy', emoji: '🫐', title: 'Blueberry Carrot Frozen Bites',
    time: 10, wait: '2 hours freezing', serves: 24, servesUnit: 'bites', tags: ['treat', 'frozen', 'no-cook', 'teething', 'low-calorie'],
    blurb: 'Light, fruity bites with almost no calories.',
    kcal: 5, kcalUnit: 'bite',
    ingredients: [[0.5, 'cup', 'blueberries'], [1, '', 'carrot, finely grated'], [0.5, 'cup', 'plain unsweetened yogurt'], [0.25, 'cup', 'water']],
    steps: ['Stir everything together.', 'Spoon into a silicone mould and freeze 2 hours.'],
    tips: ['Whole frozen blueberries and baby carrots are good treats on their own, too.'] },

  { id: 'dog-kong', kind: 'dog', course: 'Enrichment', level: 'Easy', emoji: '🧩', title: 'Frozen Stuffed Kong',
    time: 5, wait: 'overnight freezing', serves: 1, servesUnit: 'Kong', tags: ['enrichment', 'frozen', 'teething', 'no-cook'],
    blurb: 'Turns part of dinner into 30+ minutes of calm licking.',
    ingredients: [[0.33, 'of', "your dog's kibble portion, soaked in water 10 minutes"], [1, 'tbsp', 'plain canned pumpkin or plain yogurt'],
      [1, 'tsp', 'xylitol-free peanut butter'], [null, '', 'a few blueberries or carrot pieces']],
    steps: ['Smear a little peanut butter inside to plug the small hole.',
      'Mix the soaked kibble with pumpkin or yogurt and pack it in, adding blueberries as you go.',
      'Seal the top with a thin layer of pumpkin and freeze overnight.',
      'Give it in the crate or on a mat — great for settling down or alone time.'],
    tips: ['Start unfrozen and loosely packed for beginners, then make it harder.', 'Use part of the daily kibble so it does not add calories.'] },

  { id: 'dog-broth', kind: 'dog', course: 'Topper', level: 'Medium', emoji: '🍵', title: 'Dog-Safe Chicken Broth',
    time: 20, wait: '3 hours simmering', serves: 16, servesUnit: '¼-cup portions', tags: ['topper', 'freezer', 'hydration'],
    blurb: 'Plain broth to pour over kibble, freeze into cubes, or stuff in toys.',
    kcal: 10, kcalUnit: '¼ cup',
    ingredients: [[2, 'lb', 'chicken wings, backs or thighs'], [2, '', 'carrots, chopped'], [1, 'stalk', 'celery, chopped'],
      [1, 'tbsp', 'apple cider vinegar'], [10, 'cups', 'water']],
    steps: ['Put everything in a big pot, bring to a boil, then simmer gently, lid ajar, for 3 hours.',
      'Strain through a fine sieve and THROW AWAY every bone — cooked bones splinter.',
      'Chill overnight, then lift off and discard the hardened fat layer.',
      'Freeze in ice-cube trays.'],
    tips: ['Never use store-bought broth unless it says no onion, no garlic and low sodium.'] },

  { id: 'dog-liver', kind: 'dog', course: 'Treat', level: 'Medium', emoji: '🎯', title: 'Baked Liver Training Treats',
    time: 15, wait: '2 hours baking', serves: 100, servesUnit: 'tiny treats', tags: ['treat', 'high-value', 'training', 'baked'],
    blurb: 'The ultimate high-value reward for recall and hard training moments.',
    kcal: 2, kcalUnit: 'treat',
    ingredients: [[1, 'lb', 'beef or chicken liver'], [null, '', 'nothing else']],
    steps: ['Heat the oven to 250°F (120°C). Line a tray with parchment.',
      'Partly freeze the liver for 30 minutes so it slices easily, then cut into thin slices.',
      'Bake 2 hours, flipping halfway, until dry and firm.',
      'Cool, then cut into pea-sized pieces with scissors.'],
    tips: ['Liver is very rich in vitamin A — keep it as a small part of the diet (a few pieces a day, not handfuls).', 'Fridge 1 week, freezer 3 months.'] },

  { id: 'dog-egg-scramble', kind: 'dog', course: 'Topper', level: 'Easy', emoji: '🍳', title: 'Egg & Spinach Scramble',
    time: 5, serves: 2, servesUnit: 'toppers', tags: ['topper', 'quick'],
    blurb: 'A protein boost on top of breakfast kibble, once or twice a week.',
    kcal: 45, kcalUnit: 'topper',
    ingredients: [[1, '', 'egg'], [2, 'tbsp', 'baby spinach, finely chopped'], [null, '', 'no butter, oil, salt or milk']],
    steps: ['Whisk the egg with the spinach.', 'Cook in a dry non-stick pan over low heat, stirring, until fully set.', 'Cool and split into two toppers.'],
    tips: ['Always cook eggs for dogs; raw egg whites can carry salmonella.'] },
];

/* "Can my dog eat…?" Sorted roughly by how often people ask. level: safe |
   caution | toxic. Sources: ASPCA Animal Poison Control and AKC guidance. */
const DOG_FOODS = [
  { food: 'Grapes & raisins', level: 'toxic', note: 'Can cause sudden kidney failure, even in small amounts. Includes currants and sultanas, in baked goods too.' },
  { food: 'Chocolate', level: 'toxic', note: 'Theobromine. Dark and baking chocolate are the most dangerous.' },
  { food: 'Xylitol (birch sugar)', level: 'toxic', note: 'In sugar-free gum, some peanut butters, candy and baked goods. Causes a fast blood-sugar crash and liver failure.' },
  { food: 'Onion, garlic, chives, leeks', level: 'toxic', note: 'Raw, cooked or powdered — damages red blood cells. Check broths, baby food and seasonings.' },
  { food: 'Macadamia nuts', level: 'toxic', note: 'Weakness, vomiting, tremors.' },
  { food: 'Alcohol & raw yeast dough', level: 'toxic', note: 'Dough rises in the stomach and produces alcohol.' },
  { food: 'Coffee, tea, energy drinks', level: 'toxic', note: 'Caffeine affects the heart and nervous system.' },
  { food: 'Cooked bones', level: 'toxic', note: 'Splinter and can tear the gut or cause blockages.' },
  { food: 'Corn on the cob', level: 'toxic', note: 'Kernels are fine; the cob is a classic intestinal blockage.' },
  { food: 'Nutmeg', level: 'toxic', note: 'Myristicin can cause tremors and seizures in larger amounts.' },
  { food: 'Avocado', level: 'caution', note: 'The pit is a choking/blockage hazard and skin/leaves contain persin. A little flesh is not usually a problem but it is fatty — best skipped.' },
  { food: 'Cherries', level: 'caution', note: 'Flesh is OK; pits, stems and leaves contain cyanide and pits can block the gut.' },
  { food: 'Tomatoes', level: 'caution', note: 'Ripe red flesh is fine. Green tomatoes, stems and leaves are toxic.' },
  { food: 'Ham, bacon, sausage', level: 'caution', note: 'Too salty and fatty — can trigger pancreatitis.' },
  { food: 'Milk & ice cream', level: 'caution', note: 'Many dogs are lactose-intolerant. Ice cream also has sugar (and sometimes xylitol or chocolate).' },
  { food: 'Cheese', level: 'caution', note: 'Small pieces are a fine high-value treat for most dogs. High in fat; avoid with garlic/herbs.' },
  { food: 'Raw meat, fish & eggs', level: 'caution', note: 'Bacteria (salmonella, E. coli) and parasites. Raw salmon/trout from the Pacific Northwest can cause deadly salmon poisoning disease.' },
  { food: 'Citrus', level: 'caution', note: 'A segment of orange is OK; peel and seeds upset the stomach.' },
  { food: 'Mushrooms', level: 'caution', note: 'Plain store-bought are OK. Wild mushrooms can be deadly — call a vet if your dog eats one outside.' },
  { food: 'Peanut butter', level: 'caution', note: 'Great treat ONLY if xylitol-free. Read the label every time.' },
  { food: 'Carrots', level: 'safe', note: 'Raw or cooked. Crunchy, low-calorie, good frozen for teething.' },
  { food: 'Blueberries', level: 'safe', note: 'Antioxidants, tiny calories — perfect training treat.' },
  { food: 'Apple', level: 'safe', note: 'Slices are great. Remove the core and seeds.' },
  { food: 'Banana', level: 'safe', note: 'In moderation — high in sugar.' },
  { food: 'Pumpkin (plain)', level: 'safe', note: 'Plain canned or cooked — helps with both loose stools and constipation. Not pie filling (spices, sugar).' },
  { food: 'Sweet potato', level: 'safe', note: 'Cooked and plain. Never raw.' },
  { food: 'Green beans', level: 'safe', note: 'Plain, raw or steamed. A filling low-calorie snack.' },
  { food: 'Cucumber', level: 'safe', note: 'Crunchy, hydrating, almost no calories.' },
  { food: 'Watermelon', level: 'safe', note: 'Seedless flesh only; no rind.' },
  { food: 'Strawberries', level: 'safe', note: 'In moderation.' },
  { food: 'Plain cooked chicken or turkey', level: 'safe', note: 'Boneless, skinless, unseasoned.' },
  { food: 'Cooked eggs', level: 'safe', note: 'Scrambled or boiled, no butter or salt.' },
  { food: 'Cooked salmon', level: 'safe', note: 'Boneless and fully cooked. Never raw.' },
  { food: 'Plain rice & oats', level: 'safe', note: 'Cooked plain. White rice is gentlest on an upset stomach.' },
  { food: 'Plain yogurt', level: 'safe', note: 'Unsweetened, no xylitol. Small amounts.' },
  { food: 'Plain popcorn', level: 'safe', note: 'Air-popped, no butter or salt, no unpopped kernels.' },
  { food: 'Broccoli', level: 'safe', note: 'Small amounts — too much causes gas and stomach upset.' },
];

/* Healthy-eating cheat sheet for the human Guide tab. */
const HUMAN_GUIDE = [
  { title: 'Build a balanced plate', body: 'Half vegetables or fruit, a quarter protein (beans, fish, chicken, tofu, eggs), a quarter whole grains or starchy veg, plus a little healthy fat (olive oil, nuts, avocado). Drink water.' },
  { title: 'Protein at every meal', body: 'Aim for a palm-sized portion (20–30 g). It keeps you full longer and steadies energy through the afternoon.' },
  { title: 'Easy swaps', list: ['Sour cream → plain Greek yogurt', 'White rice → brown rice, quinoa or half cauliflower rice', 'Creamy dressing → olive oil + lemon or vinegar', 'Chips → roasted chickpeas or air-popped popcorn', 'Juice → whole fruit (keeps the fibre)', 'Ground beef → lean turkey or half lentils'] },
  { title: 'Batch it on Sunday', body: 'Cook one grain, roast one tray of veg, prep one protein and one sauce. Mix and match all week: bowls, wraps, salads.' },
  { title: 'Read labels for', list: ['Added sugar (under 10 g per serving is a good target)', 'Sodium (under 600 mg for a meal)', 'Fibre (3 g+ per serving is good)', 'A short ingredient list you recognise'] },
  { title: 'Food safety temperatures', list: ['Chicken & turkey: 165°F / 74°C', 'Ground meat: 160°F / 71°C', 'Fish: 145°F / 63°C', 'Leftovers: eat within 3–4 days'] },
];

/* Treat-budget guidance for the dog Guide tab. Resting energy requirement
   (RER) = 70 × kg^0.75; the multipliers are the standard vet rule of thumb. */
const DOG_LIFE_STAGES = [
  { id: 'pup4', label: 'Puppy, under 4 months', factor: 3.0 },
  { id: 'pup12', label: 'Puppy, 4–12 months', factor: 2.0 },
  { id: 'neutered', label: 'Adult, spayed/neutered', factor: 1.6 },
  { id: 'intact', label: 'Adult, intact', factor: 1.8 },
  { id: 'lose', label: 'Adult, weight loss', factor: 1.0 },
  { id: 'active', label: 'Very active / working', factor: 3.0 },
];

const DOG_RULES = [
  { title: 'The 10% rule', body: 'Treats, toppers and chews should be no more than 10% of daily calories. The rest comes from a complete, balanced food.' },
  { title: 'Homemade full meals', body: 'Home-cooked complete diets need careful balancing (calcium, vitamins, minerals). Use these recipes as treats and toppers, and ask your vet or a veterinary nutritionist before switching to homemade meals.' },
  { title: 'Never add', list: ['Onion, garlic, chives or leeks (any form)', 'Salt, butter, seasoning blends', 'Xylitol / birch sugar', 'Grapes, raisins, chocolate, macadamias'] },
  { title: 'New food? Go slow', body: 'Introduce one new thing at a time in a small amount, and wait a day to check for an upset stomach or itching.' },
  { title: 'Poison emergency', body: 'Call your vet or ASPCA Animal Poison Control (888) 426-4435 right away. Do not make your dog vomit unless a vet tells you to.' },
];
