/* Simmer content. Everything the app shows lives here so it works offline.

   Ingredient rows are [qty, unit, item]. qty is a number so the servings
   stepper can scale it (null = "to taste", never scaled). Nutrition is a rough
   per-serving estimate, labelled "approx." in the app — good enough to compare
   recipes, not to count to the gram. */

/* Every human recipe is pork-free (no pork, bacon, ham, lard or gelatin), and
   none cook with wine. check.js fails the build if one slips in.

   Recipes are the best-reviewed version of each dish on Allrecipes (the site
   with the most ratings): `rating`/`ratings` and `source` are what the source
   page showed when picked (Oct 2026). Ingredient lists come from the source;
   steps, blurbs and tips are Simmer's own words. Ranking uses a weighted score
   so 4.9★ from 12 people doesn't beat 4.8★ from 2,000. */

/* Courses in menu order. "Main" is shown as "Mains (entrées)". */
const COURSES = ['Breakfast', 'Appetizer', 'Soup & Salad', 'Main', 'Side', 'Dessert', 'Snack', 'Drink'];
const COURSE_LABEL = { Breakfast: 'Breakfast', Appetizer: 'Appetizers', 'Soup & Salad': 'Soups & Salads', Main: 'Mains (entrées)',
  Side: 'Sides', Dessert: 'Desserts', Snack: 'Snacks', Drink: 'Drinks' };
const DOG_COURSES = ['Treat', 'Topper', 'Meal', 'Enrichment'];
const LEVELS = ['Easy', 'Medium', 'Hard'];
const LEVEL_ICON = { Easy: '🟢', Medium: '🟡', Hard: '🔴' };

/* Listed west to east around the world; "group by cuisine" follows this order. */
const CUISINE_INFO = [
  { id: 'namerican', name: 'North American', region: 'The Americas', emoji: '🍁' },
  { id: 'mexican', name: 'Mexican', region: 'The Americas', emoji: '🌮' },
  { id: 'spanish', name: 'Spanish', region: 'Europe', emoji: '🥘' },
  { id: 'italian', name: 'Italian', region: 'Europe', emoji: '🍝' },
  { id: 'greek', name: 'Greek & Mediterranean', region: 'Europe', emoji: '🫒' },
  { id: 'nafrican', name: 'North African', region: 'Middle East & Africa', emoji: '🫖' },
  { id: 'mideast', name: 'Middle Eastern', region: 'Middle East & Africa', emoji: '🧆' },
  { id: 'persian', name: 'Persian', region: 'Middle East & Africa', emoji: '🍢' },
  { id: 'indian', name: 'Indian', region: 'South Asia', emoji: '🍛' },
  { id: 'thai', name: 'Thai', region: 'Southeast Asia', emoji: '🌶️' },
  { id: 'viet', name: 'Vietnamese', region: 'Southeast Asia', emoji: '🍜' },
  { id: 'chinese', name: 'Chinese', region: 'East Asia', emoji: '🥢' },
  { id: 'korean', name: 'Korean', region: 'East Asia', emoji: '🍚' },
  { id: 'japanese', name: 'Japanese', region: 'East Asia', emoji: '🍣' },
];

const RECIPES = [
  /* RATED:START */
  /* ───── Reviewed recipes (built by build_rated.py from .sources.json — edit there) ───── */
  { id: "overnight-oats", kind: "human", course: "Breakfast", cuisine: "namerican", level: "Easy", emoji: "🥣", title: "Easy Overnight Oats", time: 5, wait: "overnight", serves: 1, tags: ["vegetarian", "make-ahead", "quick"], blurb: "Oats, Greek yogurt, chia and blueberries — shake the jar tonight, eat tomorrow.", kcal: 255, protein: 13, rating: 4.8, ratings: 287,
    source: {"site": "Allrecipes", "name": "Easy Overnight Oats", "url": "https://www.allrecipes.com/recipe/244251/no-cook-overnight-oatmeal/"},
    ingredients: [[0.3333, "cup", "milk"], [0.25, "cup", "Greek yogurt"], [0.25, "cup", "rolled oats"], [2.0, "tsp", "honey"], [2.0, "tsp", "chia seeds"], [1.0, "tsp", "ground cinnamon"], [0.25, "cup", "fresh blueberries"]],
    steps: ["Put the milk, yogurt, oats, honey, chia seeds and cinnamon in a half-pint jar, close the lid and shake until mixed.", "Stir in the blueberries.", "Refrigerate at least 8 hours or overnight, then eat cold straight from the jar."],
    tips: ["Make 3–4 jars at once; they keep 3 days."] },
  { id: "egg-muffins", kind: "human", course: "Breakfast", cuisine: "namerican", level: "Easy", emoji: "🧁", title: "Muffin Pan Frittatas", time: 35, serves: 12, tags: ["high-protein", "make-ahead", "gluten-free", "vegetarian"], blurb: "Little veggie-and-cheddar frittatas you can grab all week.", kcal: 93, protein: 6, rating: 4.6, ratings: 175,
    source: {"site": "Allrecipes", "name": "Muffin Pan Frittatas", "url": "https://www.allrecipes.com/recipe/231480/muffin-pan-frittatas/"},
    ingredients: [[null, "", "cooking spray"], [1.0, "tbsp", "olive oil"], [1.0, "cup", "chopped fresh asparagus"], [0.25, "cup", "chopped green bell pepper"], [2.0, "tbsp", "chopped red onion"], [6.0, "", "eggs"], [0.5, "cup", "milk"], [0.25, "tsp", "salt"], [0.125, "tsp", "ground black pepper"], [1.0, "cup", "shredded Cheddar cheese"]],
    steps: ["Heat the oven to 350°F (175°C) and spray a 12-cup muffin tin.", "Soften the asparagus, pepper and onion in the olive oil over medium heat, 5–10 minutes.", "Whisk the eggs, milk, salt and pepper, then stir in the cooked vegetables and the cheddar.", "Spoon about ¼ cup into each cup and bake about 20 minutes, until set in the middle."],
    tips: ["Swap the asparagus for spinach or mushrooms.", "Fridge 4 days; reheat 30 seconds."] },
  { id: "avo-toast-egg", kind: "human", course: "Breakfast", cuisine: "namerican", level: "Easy", emoji: "🥑", title: "Avocado Toast with Egg", time: 10, serves: 2, tags: ["vegetarian", "quick"], blurb: "Creamy lemony avocado, a fried egg and a pinch of cayenne.", kcal: 321, protein: 12, rating: 4.9, ratings: 69,
    source: {"site": "Allrecipes", "name": "Avocado Toast with Egg", "url": "https://www.allrecipes.com/recipe/265304/avocado-toast-with-egg/"},
    ingredients: [[1.0, "tsp", "butter"], [2.0, "", "eggs"], [2.0, "slices", "multigrain bread"], [1.0, "", "ripe avocado, pitted, peeled"], [1.0, "tsp", "lemon juice, or to taste"], [1.0, "pinch", "cayenne pepper"], [null, "", "sea salt to taste"], [null, "", "ground black pepper to taste"]],
    steps: ["Melt the butter in a skillet over medium-low and fry the eggs 2–3 minutes, flip gently and cook to how you like the yolk.", "Toast the bread.", "Mash the avocado with lemon juice, cayenne and salt and spread it on the toast.", "Top each with an egg, salt and pepper."],
    tips: ["Use a little olive oil instead of butter if you prefer."] },
  { id: "banana-pancakes", kind: "human", course: "Breakfast", cuisine: "namerican", level: "Easy", emoji: "🥞", title: "Whole Wheat Oat & Banana Pancakes", time: 30, serves: 6, tags: ["vegetarian"], blurb: "Fluffy pancakes made with oat flour, whole wheat and ripe banana.", kcal: 333, protein: 11, rating: 4.7, ratings: 440,
    source: {"site": "Allrecipes", "name": "Whole Wheat, Oatmeal, and Banana Pancakes", "url": "https://www.allrecipes.com/recipe/166601/whole-wheat-oatmeal-and-banana-pancakes/"},
    ingredients: [[1.0, "cup", "uncooked rolled oats"], [1.0, "cup", "whole wheat flour"], [0.75, "cup", "all-purpose flour"], [0.25, "cup", "brown sugar"], [2.0, "tbsp", "dry milk powder"], [2.0, "tsp", "baking powder"], [0.5, "tsp", "baking soda"], [0.5, "tsp", "salt"], [2.0, "cups", "milk"], [1.0, "", "large egg"], [2.0, "tbsp", "vegetable oil"], [1.0, "tsp", "vanilla extract"], [1.0, "", "medium banana, mashed"], [1.0, "tsp", "vegetable oil, or as needed"]],
    steps: ["Blend the oats into a coarse flour.", "Whisk the oat flour with both flours, brown sugar, milk powder, baking powder, baking soda and salt.", "In another bowl whisk the milk, egg, 2 tbsp oil and vanilla, then stir in the banana.", "Stir wet into dry just until combined and rest the batter 5 minutes.", "Cook spoonfuls on an oiled griddle over medium-high about 2 minutes, until bubbles form, then flip and brown the other side."],
    tips: ["Freeze leftovers with paper between them and toast from frozen."] },
  { id: "shakshuka", kind: "human", course: "Breakfast", cuisine: "nafrican", level: "Easy", emoji: "🍳", title: "Shakshuka", time: 40, serves: 4, tags: ["vegetarian", "gluten-free", "one-pan"], blurb: "Eggs gently cooked in a spiced tomato and pepper sauce.", kcal: 209, protein: 8, rating: 4.8, ratings: 418,
    source: {"site": "Allrecipes", "name": "Shakshuka", "url": "https://www.allrecipes.com/recipe/213717/chakchouka-shakshouka/"},
    ingredients: [[3.0, "tbsp", "olive oil"], [1.3333, "cups", "chopped onion"], [1.0, "cup", "thinly sliced bell peppers, any color"], [2.0, "cloves", "garlic, minced, or to taste"], [2.5, "cups", "chopped tomatoes"], [1.0, "", "hot chile pepper, seeded and finely chopped, or to taste"], [1.0, "tsp", "ground cumin"], [1.0, "tsp", "paprika"], [1.0, "tsp", "salt"], [4.0, "", "large eggs"]],
    steps: ["Cook the onion, bell pepper and garlic in the olive oil over medium about 5 minutes, until soft.", "Mix the tomatoes with the chile, cumin, paprika and salt, add to the pan and simmer uncovered about 10 minutes, until thick.", "Make 4 hollows and slip an egg into each.", "Cover and cook about 5 minutes, until the eggs are just set. Serve with bread."],
    tips: ["Crumble feta and parsley on top for extra flavour."] },
  { id: "green-smoothie", kind: "human", course: "Drink", cuisine: "namerican", level: "Easy", emoji: "🥤", title: "Groovy Green Smoothie", time: 10, serves: 2, tags: ["vegetarian", "quick", "gluten-free"], blurb: "Spinach hidden in banana, grapes, apple and yogurt.", kcal: 205, protein: 6, rating: 4.6, ratings: 383,
    source: {"site": "Allrecipes", "name": "Groovy Green Smoothie", "url": "https://www.allrecipes.com/recipe/90329/groovy-green-smoothie/"},
    ingredients: [[1.5, "cups", "fresh spinach leaves"], [1.0, "", "banana, cut in chunks"], [1.0, "cup", "grapes"], [1.0, "tub", "vanilla yogurt (6 oz)"], [0.5, "", "apple, cored and chopped"]],
    steps: ["Put the spinach, banana, grapes, yogurt and apple in the blender.", "Blend until smooth, scraping down the sides, and pour into two glasses."],
    tips: ["Plain yogurt plus a little honey cuts the sugar.", "Freeze the grapes for a colder, thicker smoothie."] },
  { id: "hummus", kind: "human", course: "Appetizer", cuisine: "mideast", level: "Easy", emoji: "🫘", title: "Super Easy Hummus", time: 5, serves: 4, tags: ["vegan", "gluten-free", "no-cook", "quick"], blurb: "Five minutes in the food processor, no tahini needed.", kcal: 121, protein: 4, rating: 4.8, ratings: 278,
    source: {"site": "Allrecipes", "name": "Super Easy Hummus", "url": "https://www.allrecipes.com/recipe/232962/super-easy-hummus/"},
    ingredients: [[1.0, "can", "garbanzo beans, drained, liquid reserved (15 oz)"], [1.0, "tbsp", "lemon juice"], [1.0, "tbsp", "olive oil"], [1.0, "clove", "garlic, crushed"], [0.5, "tsp", "ground cumin"], [0.5, "tsp", "salt"], [2.0, "", "drops sesame oil, or to taste"]],
    steps: ["Blend the chickpeas, lemon juice, olive oil, garlic, cumin, salt and sesame oil in a food processor.", "With the motor running, pour in the saved chickpea liquid a little at a time until it is as smooth as you like.", "Serve with veggie sticks or pita."],
    tips: ["Add a spoon of tahini for a classic flavour."] },
  { id: "bruschetta", kind: "human", course: "Appetizer", cuisine: "italian", level: "Easy", emoji: "🍅", title: "Double Tomato Bruschetta", time: 35, serves: 12, tags: ["vegetarian", "party"], blurb: "Fresh and sun-dried tomatoes with basil and melted mozzarella.", kcal: 215, protein: 10, rating: 4.8, ratings: 3172,
    source: {"site": "Allrecipes", "name": "Double Tomato Bruschetta", "url": "https://www.allrecipes.com/recipe/20669/double-tomato-bruschetta/"},
    ingredients: [[6.0, "", "roma (plum) tomatoes, chopped"], [0.5, "cup", "sun-dried tomatoes, packed in oil"], [3.0, "cloves", "minced garlic"], [0.25, "cup", "olive oil"], [2.0, "tbsp", "balsamic vinegar"], [0.25, "cup", "fresh basil, stems removed"], [0.25, "tsp", "salt"], [0.25, "tsp", "ground black pepper"], [1.0, "", "French baguette"], [2.0, "cups", "shredded mozzarella cheese"]],
    steps: ["Turn on the broiler.", "Mix both tomatoes, garlic, olive oil, balsamic, basil, salt and pepper and let it sit 10 minutes.", "Slice the baguette ¾ inch thick and broil 1–2 minutes until lightly toasted.", "Spoon the tomato mix onto the toasts, top with mozzarella and broil about 5 minutes until melted."],
    tips: ["Use less cheese, or a whole-grain baguette, for a lighter version."] },
  { id: "spring-rolls", kind: "human", course: "Appetizer", cuisine: "viet", level: "Medium", emoji: "🥢", title: "Vietnamese Fresh Spring Rolls", time: 50, serves: 8, tags: ["gluten-free", "light"], blurb: "Rice-paper rolls with shrimp, noodles and herbs, plus two dipping sauces.", kcal: 82, protein: 3, rating: 4.7, ratings: 759,
    source: {"site": "Allrecipes", "name": "Vietnamese Fresh Spring Rolls", "url": "https://www.allrecipes.com/recipe/24239/vietnamese-fresh-spring-rolls/"},
    ingredients: [[2.0, "oz", "rice vermicelli"], [8.0, "", "rice wrappers (8.5 inch diameter)"], [8.0, "", "large cooked shrimp - peeled, deveined and cut in half"], [2.0, "leaves", "lettuce, chopped"], [3.0, "tbsp", "chopped fresh mint leaves"], [3.0, "tbsp", "chopped fresh cilantro"], [1.3333, "tbsp", "chopped fresh Thai basil"], [0.25, "cup", "water"], [2.0, "tbsp", "fresh lime juice"], [2.0, "tbsp", "white sugar"], [4.0, "tsp", "fish sauce"], [1.0, "clove", "garlic, minced"], [0.5, "tsp", "garlic chili sauce"], [3.0, "tbsp", "hoisin sauce"], [1.0, "tsp", "finely chopped peanuts"]],
    steps: ["Cook the vermicelli in boiling salted water 3–5 minutes, drain and cool.", "Dip a rice wrapper in warm water for about 1 second to soften and lay it flat.", "Lay 2 shrimp halves, some noodles, lettuce, mint, cilantro and basil across the middle, leaving the sides clear.", "Fold in the sides and roll up tightly. Repeat.", "Stir water, lime juice, sugar, fish sauce, garlic and chili sauce for one dip; hoisin with chopped peanuts for the other."],
    tips: ["Hoisin is gluten-free only if the label says so.", "Cover finished rolls with a damp towel."] },
  { id: "chicken-satay", kind: "human", course: "Appetizer", cuisine: "thai", level: "Medium", emoji: "🍢", title: "Easy Chicken Satay", time: 35, wait: "2 hours marinating", serves: 5, tags: ["high-protein", "party"], blurb: "Curry-coconut chicken skewers with a warm peanut sauce.", kcal: 418, protein: 24, rating: 4.7, ratings: 437,
    source: {"site": "Allrecipes", "name": "Easy Chicken Satay", "url": "https://www.allrecipes.com/recipe/132929/easy-chicken-satay/"},
    ingredients: [[0.5, "cup", "coconut milk"], [1.0, "clove", "garlic, minced"], [1.5, "tsp", "brown sugar"], [1.0, "tsp", "curry powder"], [0.5, "tsp", "salt"], [0.5, "tsp", "ground black pepper"], [0.75, "lb", "skinless, boneless chicken breast halves - cut into 1 inch strips"], [10.0, "", "wooden skewers, or as needed, soaked in water for 30 minutes (6-inch)"], [1.0, "cup", "coconut milk"], [0.75, "cup", "chicken stock"], [0.5, "cup", "creamy peanut butter"], [0.25, "cup", "brown sugar"], [1.0, "tbsp", "curry powder"], [2.0, "tbsp", "lime or lemon juice"], [1.0, "tsp", "soy sauce"], [null, "", "salt to taste"]],
    steps: ["Whisk ½ cup coconut milk with garlic, brown sugar, curry powder, salt and pepper; coat the chicken and marinate at least 2 hours.", "Heat the grill to medium-high and oil the grate. Thread the chicken onto the soaked skewers.", "For the sauce, whisk the remaining coconut milk, stock, peanut butter, brown sugar and curry powder over medium-high until simmering, then simmer about 5 minutes until thick. Stir in lime juice and soy sauce.", "Grill the skewers 4–5 minutes a side, to 165°F (74°C) inside.", "Serve with the warm sauce."],
    tips: ["Light coconut milk cuts the fat a lot."] },
  { id: "tuna-tapas", kind: "human", course: "Appetizer", cuisine: "spanish", level: "Easy", emoji: "🐟", title: "Avocado & Tuna Tapas", time: 20, serves: 4, tags: ["high-protein", "no-cook", "gluten-free"], blurb: "Avocado halves stuffed with a zesty tuna and pepper salad.", kcal: 294, protein: 24, rating: 4.7, ratings: 298,
    source: {"site": "Allrecipes", "name": "Avocado and Tuna Tapas", "url": "https://www.allrecipes.com/recipe/139620/avocado-and-tuna-tapas/"},
    ingredients: [[1.0, "can", "solid white tuna packed in water, drained (12 oz)"], [1.0, "tbsp", "mayonnaise"], [3.0, "", "green onions, thinly sliced, plus additional for garnish"], [0.5, "", "red bell pepper, chopped"], [1.0, "dash", "balsamic vinegar"], [null, "", "black pepper to taste"], [1.0, "pinch", "garlic salt, or to taste"], [2.0, "", "ripe avocados, halved and pitted"]],
    steps: ["Mix the tuna, mayonnaise, green onions, red pepper and balsamic.", "Season with pepper and garlic salt.", "Pile the tuna into the avocado halves and top with more green onion."],
    tips: ["Use Greek yogurt instead of mayo for extra protein."] },
  { id: "lentil-soup", kind: "human", course: "Soup & Salad", cuisine: "namerican", level: "Easy", emoji: "🍲", title: "Sweet Potato, Carrot, Apple & Red Lentil Soup", time: 80, serves: 6, tags: ["vegetarian", "gluten-free", "freezer"], blurb: "Velvety, gently spiced and naturally sweet.", kcal: 322, protein: 9, rating: 4.7, ratings: 1267,
    source: {"site": "Allrecipes", "name": "Sweet Potato, Carrot, Apple, and Red Lentil Soup", "url": "https://www.allrecipes.com/recipe/186378/sweet-potato-carrot-apple-and-red-lentil-soup/"},
    ingredients: [[0.25, "cup", "butter"], [2.0, "", "large sweet potatoes, peeled and chopped"], [3.0, "", "large carrots, peeled and chopped"], [1.0, "", "apple, peeled, cored and chopped"], [1.0, "", "onion, chopped"], [0.5, "cup", "red lentils"], [1.0, "tsp", "salt"], [0.5, "tsp", "minced fresh ginger"], [0.5, "tsp", "ground black pepper"], [0.5, "tsp", "ground cumin"], [0.5, "tsp", "chili powder"], [0.5, "tsp", "paprika"], [4.0, "cups", "vegetable broth"]],
    steps: ["Melt the butter in a big pot over medium-high. Cook the sweet potato, carrot, apple and onion about 10 minutes, until the onion is clear.", "Stir in the lentils and all the spices, add the broth and bring to a boil.", "Cover and simmer on medium-low about 30 minutes, until everything is soft.", "Blend until smooth, then simmer 10 minutes more, adding water if it is too thick."],
    tips: ["Use olive oil instead of butter to make it vegan.", "Freezes well for 3 months."] },
  { id: "chickpea-salad", kind: "human", course: "Soup & Salad", cuisine: "greek", level: "Easy", emoji: "🥗", title: "Mediterranean Zucchini & Chickpea Salad", time: 25, serves: 6, tags: ["vegetarian", "gluten-free", "no-cook", "make-ahead"], blurb: "Raw zucchini, chickpeas, feta and olives in a herby dressing.", kcal: 258, protein: 6, rating: 4.9, ratings: 168,
    source: {"site": "Allrecipes", "name": "Mediterranean Zucchini and Chickpea Salad", "url": "https://www.allrecipes.com/recipe/222653/mediterranean-zucchini-and-chickpea-salad/"},
    ingredients: [[2.0, "cups", "diced zucchini"], [1.0, "can", "chickpeas, drained and rinsed (15 oz)"], [1.0, "cup", "halved grape tomatoes"], [0.75, "cup", "chopped red bell pepper"], [0.5, "cup", "chopped sweet onion (such as Vidalia®)"], [0.5, "cup", "crumbled feta cheese"], [0.5, "cup", "chopped Kalamata olives"], [0.3333, "cup", "olive oil"], [0.3333, "cup", "packed fresh basil leaves, roughly chopped"], [0.25, "cup", "white balsamic vinegar"], [1.0, "tbsp", "chopped fresh rosemary"], [1.0, "tbsp", "capers, drained and chopped"], [1.0, "clove", "garlic, minced"], [0.5, "tsp", "dried Greek oregano"], [1.0, "pinch", "crushed red pepper flakes"], [null, "", "salt and ground black pepper to taste"]],
    steps: ["Dice and chop all the vegetables.", "Toss everything together in a large bowl and season with salt and pepper.", "Let it sit 15 minutes so the flavours blend."],
    tips: ["Keeps 3 days in the fridge."] },
  { id: "tabbouleh", kind: "human", course: "Soup & Salad", cuisine: "mideast", level: "Easy", emoji: "🌿", title: "Quinoa Tabbouleh", time: 30, serves: 4, tags: ["vegan", "gluten-free", "make-ahead"], blurb: "Lemony herb salad with quinoa instead of bulgur.", kcal: 354, protein: 10, rating: 4.6, ratings: 913,
    source: {"site": "Allrecipes", "name": "Quinoa Tabbouleh", "url": "https://www.allrecipes.com/recipe/25922/quinoa-tabbouleh/"},
    ingredients: [[2.0, "cups", "water"], [1.0, "cup", "quinoa"], [1.0, "pinch", "salt"], [0.25, "cup", "olive oil"], [0.5, "tsp", "sea salt"], [0.25, "cup", "lemon juice"], [3.0, "", "tomatoes, diced"], [1.0, "", "cucumber, diced"], [2.0, "bunches", "green onions, diced"], [2.0, "", "carrots, grated"], [1.0, "cup", "chopped fresh parsley"]],
    steps: ["Boil the water, add the quinoa and a pinch of salt, cover and simmer on low 15 minutes. Cool and fluff.", "Meanwhile mix the olive oil, sea salt, lemon juice, tomatoes, cucumber, green onions, carrots and parsley.", "Stir in the cooled quinoa."],
    tips: ["Even better after an hour in the fridge."] },
  { id: "beef-pho", kind: "human", course: "Soup & Salad", cuisine: "viet", level: "Hard", emoji: "🍜", title: "Beef Pho", time: 180, wait: "overnight chilling", serves: 6, tags: ["high-protein", "gluten-free", "weekend project"], blurb: "Slow-simmered beef broth with charred onion, ginger and star anise.", kcal: 885, protein: 61, rating: 4.6, ratings: 136,
    source: {"site": "Allrecipes", "name": "Beef Pho", "url": "https://www.allrecipes.com/recipe/57354/beef-pho/"},
    ingredients: [[5.0, "lb", "beef soup bones"], [1.0, "tbsp", "salt, divided"], [2.0, "gallons", "water"], [2.0, "", "medium onions, quartered"], [1.0, "", "piece fresh ginger root (4-inch)"], [2.0, "lb", "beef oxtail"], [1.0, "", "white (daikon) radish, sliced"], [2.0, "oz", "whole star anise pods"], [0.5, "", "cinnamon stick (3-inch)"], [1.0, "tsp", "black peppercorns"], [2.0, "", "whole cloves"], [1.0, "tbsp", "white sugar"], [1.0, "tbsp", "fish sauce"], [null, "", "salt to taste"], [1.5, "lb", "dried flat rice noodles"], [0.5, "lb", "frozen beef sirloin"]],
    steps: ["Cover the beef bones with the water, add 1 tsp salt, bring to a boil and simmer about 2 hours.", "Meanwhile broil the onions and ginger until charred, 10–15 minutes. Chop the onion and slice the ginger.", "Skim the broth. Add the oxtail, radish and onion, plus the ginger, star anise, cinnamon, peppercorns and cloves tied in cheesecloth. Season with sugar, fish sauce and the rest of the salt and keep simmering.", "Strain, discard the bones and spice bag, and chill the broth overnight.", "Lift off the fat, then bring the broth back to a boil.", "Soak the rice noodles in just-boiled water 6–10 minutes and slice the frozen sirloin paper-thin.", "Put noodles and raw sirloin in bowls and ladle the boiling broth over to cook the beef. Add herbs, lime and sprouts at the table."],
    tips: ["Serve with bean sprouts, Thai basil, lime, sliced chili, hoisin and sriracha.", "Broth freezes for 3 months."] },
  { id: "quinoa-salad", kind: "human", course: "Soup & Salad", cuisine: "mexican", level: "Easy", emoji: "🥙", title: "Easy Quinoa Salad", time: 30, serves: 6, tags: ["vegan", "gluten-free", "make-ahead"], blurb: "Black beans, tomatoes and cilantro in a lime-cumin dressing.", kcal: 270, protein: 9, rating: 4.8, ratings: 1543,
    source: {"site": "Allrecipes", "name": "Easy Quinoa Salad", "url": "https://www.allrecipes.com/recipe/229156/zesty-quinoa-salad/"},
    ingredients: [[2.0, "cups", "water"], [1.0, "cup", "quinoa"], [0.25, "cup", "extra-virgin olive oil"], [2.0, "", "limes, juiced"], [2.0, "tsp", "ground cumin"], [1.0, "tsp", "salt"], [0.5, "tsp", "red pepper flakes, or more to taste"], [1.5, "cups", "halved cherry tomatoes"], [1.0, "can", "black beans, drained and rinsed (15 oz)"], [5.0, "", "green onions, finely chopped"], [0.25, "cup", "chopped fresh cilantro"], [null, "", "salt and ground black pepper to taste"]],
    steps: ["Bring the water and quinoa to a boil, cover and simmer on medium-low 10–15 minutes until absorbed. Cool.", "Whisk the olive oil, lime juice, cumin, salt and pepper flakes.", "Toss the quinoa with the tomatoes, beans and green onions, pour over the dressing and stir in the cilantro."],
    tips: ["Keeps 5 days in the fridge — great for lunches."] },
  { id: "miso-soup", kind: "human", course: "Soup & Salad", cuisine: "japanese", level: "Easy", emoji: "🍵", title: "Miso Soup", time: 15, serves: 4, tags: ["quick", "light"], blurb: "Light, savoury broth with silken tofu and green onion.", kcal: 63, protein: 6, rating: 4.7, ratings: 516,
    source: {"site": "Allrecipes", "name": "Miso Soup", "url": "https://www.allrecipes.com/recipe/13107/miso-soup/"},
    ingredients: [[4.0, "cups", "water"], [2.0, "tsp", "dashi granules"], [3.0, "tbsp", "miso paste"], [1.0, "package", "silken tofu, diced (8 oz)"], [2.0, "", "green onions, sliced diagonally into 1/2 inch pieces"]],
    steps: ["Bring the water and dashi granules to a boil.", "Turn to medium and whisk in the miso paste.", "Add the tofu and green onions and simmer gently 2–3 minutes. Do not boil hard once the miso is in."],
    tips: ["Dashi is made from fish; use kombu (seaweed) dashi to make it vegan."] },
  { id: "lettuce-wraps", kind: "human", course: "Main", cuisine: "chinese", level: "Easy", emoji: "🥬", title: "Asian Lettuce Wraps", time: 30, serves: 4, tags: ["high-protein", "low-carb", "quick"], blurb: "Saucy beef and water chestnuts in crisp butter-lettuce cups.", kcal: 388, protein: 23, rating: 4.7, ratings: 2895,
    source: {"site": "Allrecipes", "name": "Asian Lettuce Wraps", "url": "https://www.allrecipes.com/recipe/71722/asian-lettuce-wraps/"},
    ingredients: [[16.0, "", "Boston Bibb or butter lettuce leaves"], [1.0, "lb", "lean ground beef"], [1.0, "tbsp", "cooking oil"], [1.0, "", "large onion, chopped"], [0.25, "cup", "hoisin sauce"], [2.0, "cloves", "fresh garlic, minced"], [1.0, "tbsp", "soy sauce"], [1.0, "tbsp", "rice vinegar"], [2.0, "tsp", "minced pickled ginger"], [1.0, "dash", "Asian chile pepper sauce, or to taste"], [1.0, "can", "water chestnuts, drained and finely chopped (8 oz)"], [1.0, "bunch", "green onions, chopped"], [2.0, "tsp", "Asian (dark) sesame oil"]],
    steps: ["Rinse and dry the lettuce leaves without tearing them.", "Brown the beef in the oil over medium-high, 5–7 minutes, then move it to a bowl and pour off the fat.", "Cook the onion in the same pan 5–7 minutes.", "Stir in the hoisin, garlic, soy sauce, rice vinegar, ginger and chile sauce, then the water chestnuts, green onions, sesame oil and beef. Cook 2 minutes.", "Spoon into the lettuce cups."],
    tips: ["Ground chicken or turkey works the same way."] },
  { id: "sheet-salmon", kind: "human", course: "Main", cuisine: "namerican", level: "Easy", emoji: "🍣", title: "Easy 5-Ingredient Salmon", time: 15, serves: 4, tags: ["high-protein", "gluten-free", "quick"], blurb: "Garlic-basil salmon pan-seared in 10 minutes.", kcal: 304, protein: 37, rating: 4.7, ratings: 671,
    source: {"site": "Allrecipes", "name": "Easy 5-Ingredient Salmon", "url": "https://www.allrecipes.com/recipe/189058/super-simple-salmon/"},
    ingredients: [[1.0, "tbsp", "garlic powder"], [1.0, "tbsp", "dried basil"], [0.5, "tsp", "salt"], [4.0, "", "fillets salmon (6 oz each)"], [2.0, "tbsp", "butter"], [4.0, "", "lemon wedges"]],
    steps: ["Mix the garlic powder, basil and salt and rub it all over the salmon.", "Melt the butter in a large skillet over medium heat.", "Cook the salmon about 5 minutes per side, until browned and flaky.", "Serve with lemon wedges."],
    tips: ["Pair with the roasted broccoli and some brown rice."] },
  { id: "chicken-stirfry", kind: "human", course: "Main", cuisine: "chinese", level: "Medium", emoji: "🥢", title: "Chicken Stir Fry", time: 40, serves: 6, tags: ["high-protein"], blurb: "Ginger-garlic chicken with lots of crunchy vegetables over rice.", kcal: 344, protein: 25, rating: 4.7, ratings: 1459,
    source: {"site": "Allrecipes", "name": "Chicken Stir Fry", "url": "https://www.allrecipes.com/recipe/223382/chicken-stir-fry/"},
    ingredients: [[4.0, "cups", "water"], [2.0, "cups", "white rice"], [0.6667, "cup", "soy sauce"], [0.25, "cup", "brown sugar"], [1.0, "tbsp", "cornstarch"], [1.0, "tbsp", "minced fresh ginger"], [1.0, "tbsp", "minced garlic"], [0.25, "tsp", "red pepper flakes"], [3.0, "", "skinless, boneless chicken breast halves, thinly sliced"], [2.0, "tbsp", "sesame oil, divided"], [1.0, "head", "broccoli, broken into florets"], [1.0, "", "onion, cut into large chunks"], [1.0, "cup", "sliced carrots"], [1.0, "can", "sliced water chestnuts, drained (8 oz)"], [1.0, "", "green bell pepper, cut into matchsticks"]],
    steps: ["Simmer the rice in the water, covered, 20–25 minutes.", "Stir the soy sauce, brown sugar and cornstarch smooth, add the ginger, garlic and pepper flakes, and marinate the chicken in it at least 15 minutes.", "Stir-fry the vegetables in 1 tbsp sesame oil over medium-high about 5 minutes, then set aside.", "Heat the rest of the oil, sear the chicken (keep the marinade) about 2 minutes a side.", "Add the vegetables and marinade, bring to a boil and cook 5–7 minutes until the chicken is cooked through. Serve over the rice."],
    tips: ["Low-sodium soy sauce and brown rice make it lighter."] },
  { id: "turkey-chili", kind: "human", course: "Main", cuisine: "mexican", level: "Easy", emoji: "🌶️", title: "Terrific Turkey Chili", time: 70, serves: 6, tags: ["high-protein", "gluten-free", "freezer"], blurb: "Taco-spiced turkey chili loaded with zucchini and peppers.", kcal: 506, protein: 35, rating: 4.8, ratings: 1098,
    source: {"site": "Allrecipes", "name": "Terrific Turkey Chili", "url": "https://www.allrecipes.com/recipe/62763/terrific-turkey-chili/"},
    ingredients: [[3.0, "tbsp", "vegetable oil, divided"], [1.5, "lb", "ground turkey"], [1.0, "package", "taco seasoning mix (1 oz)"], [1.0, "tsp", "ground coriander"], [1.0, "tsp", "dried oregano"], [1.0, "tsp", "chili pepper flakes"], [2.0, "tbsp", "tomato paste"], [1.0, "can", "beef broth (14.5 oz)"], [1.0, "can", "salsa (7 oz)"], [1.0, "can", "crushed tomatoes, or coarsely chopped tomatoes packed in puree (14.5 oz)"], [1.0, "can", "chopped green chile peppers (7 oz)"], [1.0, "", "medium onion, finely chopped"], [1.0, "", "green bell pepper, diced"], [3.0, "", "medium zucchini, halved lengthwise and sliced"], [1.0, "bunch", "green onions, chopped"], [1.0, "cup", "sour cream"], [1.0, "cup", "shredded Cheddar cheese"]],
    steps: ["Brown the turkey in 1 tbsp oil in a big pot, breaking it up, then season with the taco mix, coriander, oregano, chili flakes and tomato paste.", "Add the broth and simmer 5 minutes, then add the salsa, tomatoes and green chiles and simmer 10 minutes.", "Meanwhile cook the onion and pepper in 1 tbsp oil 5 minutes and add to the chili.", "Brown the zucchini in the last tbsp oil 5 minutes, add it, and simmer 15 minutes more.", "Top with sour cream, green onion and cheddar."],
    tips: ["Greek yogurt instead of sour cream adds protein.", "Check the taco seasoning label if you need it gluten-free."] },
  { id: "shrimp-tacos", kind: "human", course: "Main", cuisine: "mexican", level: "Easy", emoji: "🌮", title: "Shrimp Tacos with Mango Salsa", time: 50, serves: 4, tags: ["high-protein"], blurb: "Sweet-buttery shrimp with a fresh mango-avocado salsa.", kcal: 567, protein: 31, rating: 4.7, ratings: 161,
    source: {"site": "Allrecipes", "name": "Shrimp Tacos", "url": "https://www.allrecipes.com/recipe/139830/shrimp-tacos/"},
    ingredients: [[2.0, "", "tomatoes, diced"], [1.0, "", "mango - peeled, seeded and diced"], [1.0, "", "ripe avocado - peeled, pitted, and diced"], [0.5, "cup", "chopped fresh cilantro"], [0.25, "cup", "chopped red onion"], [2.0, "tbsp", "lime juice"], [3.0, "cloves", "garlic, minced"], [0.5, "tsp", "salt"], [0.25, "cup", "honey butter"], [1.0, "lb", "salad shrimp"], [4.0, "", "flour tortillas, warmed (10-inch)"]],
    steps: ["Toss the tomatoes, mango, avocado, cilantro, onion, lime juice, garlic and salt and chill 30 minutes.", "Melt the honey butter in a skillet over medium-high and cook the shrimp 2–3 minutes, until pink.", "Fill the warm tortillas with shrimp and salsa."],
    tips: ["Corn tortillas make it lighter and gluten-free."] },
  { id: "chickpea-curry", kind: "human", course: "Main", cuisine: "indian", level: "Easy", emoji: "🍛", title: "Creamy Chickpea Curry", time: 45, serves: 6, tags: ["vegan", "one-pot"], blurb: "Potatoes, cauliflower and chickpeas in a coconut curry sauce.", kcal: 420, protein: 11, rating: 4.7, ratings: 149,
    source: {"site": "Allrecipes", "name": "Creamy Chickpea Curry", "url": "https://www.allrecipes.com/recipe/254692/crazy-creamy-chickpea-curry/"},
    ingredients: [[1.0, "tbsp", "coconut oil"], [1.0, "", "medium yellow onion, thinly sliced"], [1.0, "tbsp", "minced fresh ginger root"], [4.0, "cloves", "garlic, minced"], [2.0, "tbsp", "mild curry powder"], [0.25, "tsp", "red pepper flakes"], [2.5, "cups", "vegetable broth"], [2.0, "tbsp", "reduced-sodium soy sauce or tamari"], [2.0, "tbsp", "pure maple syrup"], [2.0, "tbsp", "tomato paste"], [0.75, "lb", "Yukon Gold potatoes, cut into 3/4-inch pieces"], [1.0, "", "large carrot, sliced diagonally 1/4 inch thick"], [4.0, "cups", "large cauliflower florets"], [1.0, "can", "chickpeas, rinsed and drained (15 oz)"], [1.0, "cup", "coconut milk"], [0.25, "cup", "chopped fresh cilantro, plus more for garnish"], [0.5, "cup", "frozen peas"], [null, "", "salt"], [null, "", "Cooked basmati rice"], [1.0, "tbsp", "Sriracha chile sauce"]],
    steps: ["Brown the onion in the coconut oil 5–7 minutes, then add the ginger and garlic for 30 seconds.", "Stir in the curry powder, pepper flakes, broth, soy sauce, maple syrup and tomato paste.", "Add the potatoes and carrot, cover, bring to a boil and simmer with the lid ajar about 10 minutes.", "Add the cauliflower, chickpeas, coconut milk and cilantro and simmer until the cauliflower is tender, then stir in the peas.", "Season and serve over basmati rice with sriracha on the side."],
    tips: ["Use tamari to make it gluten-free."] },
  { id: "zucchini-lasagna", kind: "human", course: "Main", cuisine: "italian", level: "Medium", emoji: "🍝", title: "Zucchini Lasagna", time: 80, serves: 6, tags: ["low-carb", "gluten-free", "high-protein"], blurb: "Lasagna layered with zucchini instead of noodles.", kcal: 424, protein: 30, rating: 4.9, ratings: 169,
    source: {"site": "Allrecipes", "name": "Zucchini Lasagna", "url": "https://www.allrecipes.com/recipe/261026/ultimate-low-carb-zucchini-lasagna/"},
    ingredients: [[null, "", "cooking spray"], [1.5, "", "large zucchinis, thinly sliced lengthwise"], [1.0, "tbsp", "olive oil"], [1.0, "lb", "ground beef"], [1.5, "cups", "low-carb marinara sauce"], [2.0, "tsp", "salt, divided"], [1.0, "tsp", "dried oregano"], [0.5, "tsp", "ground black pepper"], [1.0, "container", "ricotta cheese (8 oz)"], [1.0, "", "large egg"], [0.5, "tsp", "ground nutmeg"], [2.0, "cups", "shredded mozzarella cheese"], [0.25, "cup", "grated Parmesan cheese"], [null, "", "aluminum foil"]],
    steps: ["Heat the oven to 375°F (190°C) and grease an 8-inch square dish. Pat the zucchini slices dry.", "Brown the beef in the olive oil 5–8 minutes, add the marinara, 1 tsp salt, oregano and pepper, and simmer 10 minutes.", "Mix the ricotta, egg, 1 tsp salt and nutmeg.", "Layer: zucchini, half the sauce, zucchini, the ricotta, half the mozzarella, zucchini, the rest of the sauce and mozzarella, then the parmesan.", "Cover with foil and bake 30 minutes, then uncover and bake about 15 minutes more until golden."],
    tips: ["Salt the zucchini slices and leave 15 minutes before patting dry for a less watery lasagna."] },
  { id: "greek-chicken", kind: "human", course: "Main", cuisine: "greek", level: "Easy", emoji: "🍗", title: "Greek Lemon Chicken & Potato Bake", time: 70, serves: 4, tags: ["high-protein", "gluten-free", "one-pan"], blurb: "Lemon-herb chicken quarters, potatoes and green beans on one tray.", kcal: 551, protein: 35, rating: 4.6, ratings: 894,
    source: {"site": "Allrecipes", "name": "Greek Lemon Chicken and Potato Bake", "url": "https://www.allrecipes.com/recipe/242402/greek-lemon-chicken-and-potato-bake/"},
    ingredients: [[4.0, "", "chicken leg quarters"], [1.0, "bag", "small potatoes (24 oz)"], [0.5, "cup", "olive oil"], [2.0, "", "lemons, juiced, divided"], [2.0, "tbsp", "dried basil"], [2.0, "tbsp", "dried oregano"], [1.0, "tbsp", "salt"], [1.0, "tbsp", "ground black pepper"], [2.0, "tbsp", "lemon and herb seasoning"], [1.0, "package", "fresh green beans (12 oz)"]],
    steps: ["Heat the oven to 425°F (220°C) and grease a large rimmed tray. Put the chicken on it.", "Toss the potatoes with the olive oil, juice of 1 lemon, basil, oregano, salt, pepper and lemon-herb seasoning. Arrange around the chicken and pour most of the oil mix over; keep a little.", "Bake 30 minutes, shake the tray and bake 15 minutes more.", "Toss the green beans in the reserved oil, scatter over the tray and bake about 15 minutes, until the chicken reaches 165°F (74°C). Squeeze over the second lemon."],
    tips: ["Use skinless thighs and half the oil for a lighter version."] },
  { id: "teriyaki-chicken", kind: "human", course: "Main", cuisine: "japanese", level: "Easy", emoji: "🍱", title: "Baked Teriyaki Chicken", time: 65, serves: 6, tags: ["high-protein"], blurb: "Sticky homemade teriyaki baked onto juicy chicken thighs.", kcal: 272, protein: 25, rating: 4.7, ratings: 7729,
    source: {"site": "Allrecipes", "name": "Baked Teriyaki Chicken", "url": "https://www.allrecipes.com/recipe/9023/baked-teriyaki-chicken/"},
    ingredients: [[0.5, "cup", "white sugar"], [0.5, "cup", "soy sauce"], [0.25, "cup", "cider vinegar"], [1.0, "tbsp", "cornstarch"], [1.0, "tbsp", "cold water"], [1.0, "clove", "garlic, minced"], [0.5, "tsp", "ground ginger"], [0.25, "tsp", "ground black pepper"], [12.0, "", "boneless, skinless chicken thighs"]],
    steps: ["Heat the oven to 425°F (220°C) and grease a 9×13 dish.", "Simmer the sugar, soy sauce, vinegar, cornstarch, water, garlic, ginger and pepper over low 3–5 minutes, until thick.", "Brush the chicken all over with sauce and bake 30 minutes.", "Flip, brush again, and bake 20–30 minutes more, basting every 10 minutes, until cooked through."],
    tips: ["Halve the sugar for a less sweet sauce.", "Serve over rice with steamed broccoli."] },
  { id: "black-bean-burgers", kind: "human", course: "Main", cuisine: "namerican", level: "Easy", emoji: "🍔", title: "Quinoa Black Bean Burgers", time: 35, serves: 5, tags: ["vegetarian", "freezer"], blurb: "Hearty, spicy-edged patties that hold together.", kcal: 245, protein: 9, rating: 4.7, ratings: 1165,
    source: {"site": "Allrecipes", "name": "Quinoa Black Bean Burgers", "url": "https://www.allrecipes.com/recipe/220661/quinoa-black-bean-burgers/"},
    ingredients: [[0.5, "cup", "water"], [0.25, "cup", "quinoa"], [1.0, "can", "black beans, rinsed and drained (15 oz)"], [0.5, "cup", "bread crumbs"], [0.25, "cup", "minced yellow bell pepper"], [1.0, "", "large egg"], [2.0, "tbsp", "minced onion"], [1.0, "", "large clove garlic, minced"], [1.5, "tsp", "ground cumin"], [1.0, "tsp", "hot pepper sauce (such as Frank's RedHot®)"], [0.5, "tsp", "salt"], [3.0, "tbsp", "olive oil"]],
    steps: ["Simmer the quinoa in the water, covered, 15–20 minutes until absorbed.", "Mash the beans roughly, then mix in the quinoa, bread crumbs, pepper, egg, onion, garlic, cumin, hot sauce and salt. Shape 5 patties.", "Heat the olive oil in a skillet over medium.", "Cook the patties 2–3 minutes a side until browned and hot through."],
    tips: ["Freeze uncooked patties between parchment."] },
  { id: "tikka-masala", kind: "human", course: "Main", cuisine: "indian", level: "Medium", emoji: "🍛", title: "Curry Stand Chicken Tikka Masala", time: 80, serves: 6, tags: ["high-protein", "gluten-free"], blurb: "The most-loved tikka masala on Allrecipes: rich, warmly spiced, a little sweet.", kcal: 362, protein: 28, rating: 4.9, ratings: 2420,
    source: {"site": "Allrecipes", "name": "Curry Stand Chicken Tikka Masala Sauce", "url": "https://www.allrecipes.com/recipe/228293/curry-stand-chicken-tikka-masala-sauce/"},
    ingredients: [[2.0, "tbsp", "ghee (clarified butter)"], [1.0, "", "onion, finely chopped"], [4.0, "cloves", "garlic, minced"], [1.0, "tbsp", "ground cumin"], [1.0, "tsp", "salt, or more to taste"], [1.0, "tsp", "ground ginger"], [1.0, "tsp", "cayenne pepper"], [0.5, "tsp", "ground cinnamon"], [0.25, "tsp", "ground turmeric"], [1.0, "can", "tomato sauce (14 oz)"], [1.0, "cup", "heavy whipping cream"], [1.0, "tbsp", "white sugar, or more to taste"], [2.0, "tsp", "paprika"], [1.0, "tbsp", "vegetable oil"], [4.0, "", "skinless, boneless chicken breast halves, cut into bite-size pieces"], [0.5, "tsp", "curry powder"]],
    steps: ["Cook the onion in the ghee over medium about 5 minutes, add the garlic for 1 minute.", "Add the cumin, salt, ginger, cayenne, cinnamon and turmeric and fry 2 minutes.", "Add the tomato sauce, bring to a boil and simmer 10 minutes on low.", "Stir in the cream, sugar and paprika and simmer, stirring, 10–15 minutes until thick.", "Sear the chicken with the curry powder in the oil about 3 minutes.", "Add the chicken to the sauce and simmer about 30 minutes until cooked through. Adjust salt and sugar."],
    tips: ["Lighter swap: half-and-half or Greek yogurt (stirred in off the heat) instead of heavy cream.", "Serve with basmati rice or naan."] },
  { id: "tagine", kind: "human", course: "Main", cuisine: "nafrican", level: "Easy", emoji: "🫖", title: "Easy Moroccan Chicken Tagine", time: 60, serves: 6, tags: ["high-protein", "gluten-free", "one-pot"], blurb: "Chicken, butternut squash and chickpeas simmered with coriander and lemon.", kcal: 266, protein: 14, rating: 4.5, ratings: 440,
    source: {"site": "Allrecipes", "name": "Easy Moroccan Chicken Tagine", "url": "https://www.allrecipes.com/recipe/69633/stovetop-moroccan-tagine/"},
    ingredients: [[1.0, "tbsp", "olive oil"], [2.0, "", "skinless, boneless chicken breast halves - cut into chunks"], [0.5, "", "medium onion, chopped"], [3.0, "cloves", "garlic, minced"], [1.0, "", "small butternut squash, peeled and chopped"], [1.0, "can", "chickpeas, drained and rinsed (15.5 oz)"], [1.0, "can", "diced tomatoes, undrained (14.5 oz)"], [1.0, "can", "vegetable broth (14 oz)"], [1.0, "", "medium carrot, peeled and chopped"], [1.0, "tbsp", "sugar"], [1.0, "tbsp", "lemon juice"], [1.0, "tsp", "salt"], [1.0, "tsp", "ground coriander"], [1.0, "pinch", "cayenne pepper"]],
    steps: ["Cook the chicken, onion and garlic in the oil over medium about 15 minutes, until browned.", "Add the squash, chickpeas, tomatoes with their juice, broth, carrot, sugar, lemon juice, salt, coriander and cayenne.", "Bring to a boil, then simmer about 30 minutes until the vegetables are tender."],
    tips: ["Serve over couscous or quinoa."] },
  { id: "kofta", kind: "human", course: "Main", cuisine: "mideast", level: "Medium", emoji: "🍢", title: "Kofta Kebabs", time: 50, wait: "30 min chilling", serves: 28, servesUnit: "kebabs", tags: ["high-protein", "gluten-free", "party"], blurb: "Spiced lamb skewers with parsley, cinnamon and allspice.", kcal: 35, protein: 3, kcalUnit: "kebab", rating: 4.7, ratings: 432,
    source: {"site": "Allrecipes", "name": "Kofta Kebabs", "url": "https://www.allrecipes.com/recipe/106030/kofta-kebabs/"},
    ingredients: [[4.0, "cloves", "garlic, minced"], [1.0, "tsp", "kosher salt"], [1.0, "lb", "ground lamb"], [3.0, "tbsp", "grated onion"], [3.0, "tbsp", "chopped fresh parsley"], [1.0, "tbsp", "ground coriander"], [1.0, "tsp", "ground cumin"], [0.5, "tbsp", "ground cinnamon"], [0.5, "tsp", "ground allspice"], [0.25, "tsp", "cayenne pepper"], [0.25, "tsp", "ground ginger"], [0.25, "tsp", "ground black pepper"], [28.0, "", "bamboo skewers, soaked in water for 30 minutes"]],
    steps: ["Mash the garlic and salt into a paste.", "Mix it into the lamb with the onion, parsley and all the spices.", "Shape into 28 balls, press each onto a soaked skewer as a 2-inch oval, and chill at least 30 minutes.", "Grill over medium, turning, 5–6 minutes until browned and cooked through (145°F / 63°C)."],
    tips: ["Serve with tzatziki or the cucumber raita, salad and warm pita.", "Ground beef works too."] },
  { id: "falafel", kind: "human", course: "Main", cuisine: "mideast", level: "Medium", emoji: "🧆", title: "Sean's Falafel with Cucumber Sauce", time: 60, serves: 4, tags: ["vegetarian"], blurb: "Crisp chickpea falafel in pita with a cool yogurt-dill sauce.", kcal: 586, protein: 15, rating: 4.6, ratings: 1529,
    source: {"site": "Allrecipes", "name": "Sean’s Falafel and Cucumber Sauce", "url": "https://www.allrecipes.com/recipe/25309/seans-falafel-and-cucumber-sauce/"},
    ingredients: [[1.0, "container", "plain yogurt (6 oz)"], [0.5, "", "cucumber - peeled, seeded, and finely chopped"], [1.0, "tbsp", "mayonnaise"], [1.0, "tsp", "dried dill weed"], [null, "", "salt and pepper to taste"], [1.0, "can", "chickpeas (garbanzo beans), drained (15 oz)"], [1.0, "", "onion, chopped"], [0.5, "cup", "fresh parsley"], [2.0, "cloves", "garlic, chopped"], [1.0, "", "egg"], [2.0, "tsp", "ground cumin"], [1.0, "tsp", "ground coriander"], [1.0, "tsp", "salt"], [1.0, "tsp", "lemon juice"], [1.0, "tsp", "baking powder"], [1.0, "dash", "pepper"], [1.0, "pinch", "cayenne pepper"], [1.0, "tbsp", "olive oil"], [1.0, "cup", "dry bread crumbs"], [null, "", "oil for frying"], [2.0, "", "pita breads, cut in half"], [1.0, "cup", "chopped tomatoes"]],
    steps: ["Mix the yogurt, cucumber, mayonnaise, dill, salt and pepper and chill at least 30 minutes.", "Mash the chickpeas by hand until thick and pasty.", "Blend the onion, parsley and garlic and stir into the chickpeas.", "Mix in the egg, spices, salt, lemon juice, baking powder and olive oil, then add bread crumbs until the mix holds together. Shape into small patties.", "Fry in about 1 inch of hot oil until brown on both sides.", "Serve 2 in each pita half with tomatoes and sauce."],
    tips: ["Lighter: brush with oil and bake at 400°F (200°C) about 20 minutes, flipping once."] },
  { id: "bibimbap", kind: "human", course: "Main", cuisine: "korean", level: "Medium", emoji: "🍚", title: "Vegetarian Bibimbap", time: 50, serves: 3, tags: ["vegetarian"], blurb: "Sesame vegetables and seasoned rice topped with a runny egg.", kcal: 395, protein: 14, rating: 4.6, ratings: 192,
    source: {"site": "Allrecipes", "name": "Vegetarian Bibimbap", "url": "https://www.allrecipes.com/recipe/228241/vegetarian-bibimbap/"},
    ingredients: [[2.0, "tbsp", "sesame oil"], [1.0, "cup", "carrot matchsticks"], [1.0, "cup", "zucchini matchsticks"], [0.5, "can", "bean sprouts, drained (14 oz)"], [6.0, "oz", "canned bamboo shoots, drained"], [1.0, "can", "sliced mushrooms, drained (4.5 oz)"], [0.125, "tsp", "salt to taste"], [2.0, "cups", "cooked and cooled rice"], [0.3333, "cup", "sliced green onions"], [2.0, "tbsp", "soy sauce"], [0.25, "tsp", "ground black pepper"], [1.0, "tbsp", "butter"], [3.0, "", "eggs"], [3.0, "tsp", "sweet red chili sauce, or to taste"]],
    steps: ["Cook the carrot and zucchini in the sesame oil over medium about 5 minutes, then add the sprouts, bamboo shoots and mushrooms and cook until the carrots are tender.", "In the same pan stir the rice, green onions, soy sauce and pepper until hot.", "Fry the eggs in butter until the whites are set but the yolks are runny.", "Divide the rice, top with vegetables and an egg, and serve with sweet chili sauce."],
    tips: ["Use fresh vegetables instead of canned if you have them.", "Gochujang is the classic sauce (some brands contain alcohol — check the label)."] },
  { id: "raita", kind: "human", course: "Side", cuisine: "indian", level: "Easy", emoji: "🥒", title: "Cucumber Raita", time: 10, wait: "a few hours chilling", serves: 24, tags: ["vegetarian", "gluten-free", "no-cook"], blurb: "Cool minty yogurt to go with curries and kebabs.", kcal: 14, protein: 2, rating: 4.5, ratings: 135,
    source: {"site": "Allrecipes", "name": "Cucumber Raita", "url": "https://www.allrecipes.com/recipe/105046/cucumber-raita/"},
    ingredients: [[2.0, "cups", "Greek yogurt"], [2.0, "", "hot house cucumber - peeled, seeded and thinly sliced"], [3.0, "tbsp", "lemon juice"], [2.0, "tbsp", "chopped fresh mint"], [0.5, "tsp", "white sugar"], [0.25, "tsp", "kosher salt"]],
    steps: ["Stir the yogurt, cucumber, lemon juice, mint, sugar and salt together.", "Cover and chill a few hours or overnight for the best flavour."],
    tips: ["A pinch of toasted cumin is a nice addition."] },
  { id: "street-corn", kind: "human", course: "Side", cuisine: "mexican", level: "Easy", emoji: "🌽", title: "Mexican Street Corn Salad", time: 20, serves: 8, tags: ["vegetarian", "gluten-free", "quick"], blurb: "Warm corn with cotija, lime and chili — elote in a bowl.", kcal: 141, protein: 4, rating: 4.7, ratings: 91,
    source: {"site": "Allrecipes", "name": "Mexican Street Corn Salad", "url": "https://www.allrecipes.com/recipe/217842/mexican-street-vendor-style-corn-salad/"},
    ingredients: [[2.0, "", "cans whole kernel corn, undrained (15.25 oz each)"], [0.25, "cup", "grated cotija cheese"], [2.0, "tbsp", "mayonnaise"], [2.0, "tbsp", "lime juice, or to taste"], [1.0, "tbsp", "butter"], [1.0, "pinch", "ground red pepper to taste"], [1.0, "sprig", "cilantro for garnish"]],
    steps: ["Bring the corn and its liquid to a boil, then drain and put back in the pan.", "Stir in the cotija, mayonnaise, lime juice, butter and chili.", "Garnish with cilantro."],
    tips: ["Char the corn in a hot dry pan for a smokier taste."] },
  { id: "roast-broccoli", kind: "human", course: "Side", cuisine: "namerican", level: "Easy", emoji: "🥦", title: "Easy Roasted Broccoli", time: 30, serves: 4, tags: ["vegan", "gluten-free"], blurb: "Three ingredients, crispy edges, and the stalks too.", kcal: 63, protein: 3, rating: 4.7, ratings: 186,
    source: {"site": "Allrecipes", "name": "Easy Roasted Broccoli", "url": "https://www.allrecipes.com/recipe/240438/easy-roasted-broccoli/"},
    ingredients: [[14.0, "oz", "broccoli"], [1.0, "tbsp", "olive oil"], [null, "", "salt and ground black pepper to taste"]],
    steps: ["Heat the oven to 400°F (200°C).", "Cut the florets off; peel the stalk and slice it ¼ inch thick.", "Toss with olive oil, spread on a tray and season.", "Roast 18–20 minutes until tender and browned."],
    tips: ["Finish with lemon and a little parmesan."] },
  { id: "sunomono", kind: "human", course: "Side", cuisine: "japanese", level: "Easy", emoji: "🥒", title: "Sunomono (Japanese Cucumber Salad)", time: 15, serves: 5, tags: ["vegan", "gluten-free", "no-cook", "light"], blurb: "Thin cucumber in a sweet-sour rice vinegar and ginger dressing.", kcal: 27, protein: 1, rating: 4.7, ratings: 347,
    source: {"site": "Allrecipes", "name": "Sunomono (Japanese Cucumber Salad)", "url": "https://www.allrecipes.com/recipe/14050/cucumber-sunomono/"},
    ingredients: [[2.0, "", "large cucumbers, peeled"], [0.3333, "cup", "rice vinegar"], [4.0, "tsp", "white sugar"], [1.5, "tsp", "minced fresh ginger root"], [1.0, "tsp", "salt"]],
    steps: ["Halve the cucumbers lengthwise, scoop out big seeds and slice very thinly.", "Mix the rice vinegar, sugar, ginger and salt.", "Toss the cucumber in the dressing and serve chilled."],
    tips: ["Add sesame seeds or a few cooked shrimp to make it a starter."] },
  { id: "persian-rice", kind: "human", course: "Side", cuisine: "persian", level: "Hard", emoji: "🍚", title: "Persian Rice with Potato Tahdig", time: 70, serves: 8, tags: ["vegetarian", "gluten-free"], blurb: "Fluffy saffron basmati over a golden, crispy potato crust.", kcal: 255, protein: 4, rating: 4.7, ratings: 102,
    source: {"site": "Allrecipes", "name": "Persian Rice", "url": "https://www.allrecipes.com/recipe/240606/persian-rice/"},
    ingredients: [[3.0, "quarts", "water"], [3.0, "tbsp", "kosher salt"], [2.0, "cups", "basmati rice, rinsed"], [2.0, "tbsp", "olive oil"], [1.0, "", "russet potato, cut into 1/4-inch slices"], [1.0, "pinch", "ground cumin"], [null, "", "salt to taste"], [3.0, "tbsp", "butter, cut into thin slices, or to taste"], [1.0, "pinch", "saffron threads"], [1.5, "tbsp", "hot water"], [1.0, "tbsp", "chopped parsley, or to taste"]],
    steps: ["Boil the salted water, add the rice and cook exactly 7 minutes. Drain.", "Heat the oil in a pot over medium-high, cover the bottom with potato slices, sprinkle with cumin and salt and fry until sizzling, 2–3 minutes.", "Pile the rice on top, lower the heat and dot with butter.", "Cover with paper towels under the lid and steam about 45 minutes, until fluffy and the potatoes are crisp.", "Grind the saffron, steep in the hot water, and stir a few spoons of rice into it until golden.", "Serve the rice topped with the saffron rice, the crispy potatoes around the edge, and parsley."],
    tips: ["Pairs beautifully with the kofta kebabs."] },
  { id: "mango-chia", kind: "human", course: "Dessert", cuisine: "thai", level: "Easy", emoji: "🥥", title: "Chia Coconut Pudding", time: 10, wait: "20 min – overnight", serves: 6, tags: ["vegan", "gluten-free", "make-ahead"], blurb: "Creamy coconut chia pudding topped with fresh strawberries.", kcal: 243, protein: 4, rating: 4.8, ratings: 68,
    source: {"site": "Allrecipes", "name": "Chia Coconut Pudding with Coconut Milk", "url": "https://www.allrecipes.com/recipe/237469/chia-coconut-pudding-with-coconut-milk/"},
    ingredients: [[2.0, "cups", "sweetened coconut milk"], [6.0, "tbsp", "unsweetened coconut milk"], [1.0, "tbsp", "agave nectar, or more to taste"], [0.5, "tsp", "vanilla extract"], [0.25, "tsp", "ground cinnamon"], [1.0, "pinch", "salt"], [0.5, "cup", "chia seeds"], [0.5, "cup", "diced fresh strawberries"]],
    steps: ["Whisk both coconut milks with the agave, vanilla, cinnamon and salt, then stir in the chia seeds.", "Let it thicken at least 20 minutes, or cover and chill overnight.", "Stir and top with strawberries."],
    tips: ["Diced mango is delicious instead of strawberries.", "Unsweetened coconut milk cuts the sugar."] },
  { id: "baked-apples", kind: "human", course: "Dessert", cuisine: "namerican", level: "Easy", emoji: "🍎", title: "Baked Apples", time: 50, serves: 4, tags: ["vegetarian", "gluten-free"], blurb: "Tart apples stuffed with cinnamon sugar and baked until tender.", kcal: 210, protein: 1, rating: 4.6, ratings: 259,
    source: {"site": "Allrecipes", "name": "Baked Apples", "url": "https://www.allrecipes.com/recipe/21127/baked-apples/"},
    ingredients: [[4.0, "", "tart green apples"], [0.5, "cup", "brown sugar"], [2.0, "tsp", "ground cinnamon"], [0.25, "tsp", "kosher salt"], [4.0, "tbsp", "butter"]],
    steps: ["Heat the oven to 350°F (175°C).", "Core each apple from the top, leaving the bottom 1½ inches intact.", "Mix the brown sugar, cinnamon and salt and fill each apple with about 2 tbsp.", "Stand them in an 8-inch dish, top each with a piece of butter, add ¼ inch boiling water and cover with foil.", "Bake 20 minutes, uncover and bake 20–25 minutes more until tender."],
    tips: ["Serve with plain Greek yogurt instead of ice cream."] },
  { id: "berry-crisp", kind: "human", course: "Dessert", cuisine: "namerican", level: "Easy", emoji: "🫐", title: "Triple Berry Crisp", time: 50, serves: 18, tags: ["vegetarian", "party"], blurb: "Blackberries, raspberries and blueberries under a buttery oat crumble.", kcal: 295, protein: 3, rating: 4.7, ratings: 1344,
    source: {"site": "Allrecipes", "name": "Triple Berry Crisp", "url": "https://www.allrecipes.com/recipe/52547/triple-berry-crisp/"},
    ingredients: [[1.5, "cups", "fresh blackberries"], [1.5, "cups", "fresh raspberries"], [1.5, "cups", "fresh blueberries"], [0.25, "cup", "white sugar"], [2.0, "cups", "all-purpose flour"], [2.0, "cups", "rolled oats"], [1.5, "cups", "packed brown sugar"], [1.0, "tsp", "ground cinnamon"], [0.5, "tsp", "ground nutmeg"], [1.5, "cups", "cold butter, cubed"]],
    steps: ["Heat the oven to 350°F (175°C).", "Gently toss the berries with the white sugar.", "Mix the flour, oats, brown sugar, cinnamon and nutmeg, then cut in the butter until crumbly.", "Press half the crumble into a 9×13 pan, add the berries and sprinkle over the rest.", "Bake 30–40 minutes until bubbling and golden."],
    tips: ["Serves 18 — a party dessert. For a lighter version, halve the butter and brown sugar and use only a topping layer."] },
  { id: "fruit-salad", kind: "human", course: "Dessert", cuisine: "namerican", level: "Easy", emoji: "🍓", title: "Perfect Summer Fruit Salad", time: 30, wait: "3 hours chilling", serves: 10, tags: ["vegan", "gluten-free", "make-ahead", "party"], blurb: "Layers of fresh fruit in a citrus-vanilla syrup.", kcal: 277, protein: 4, rating: 4.8, ratings: 591,
    source: {"site": "Allrecipes", "name": "Perfect Summer Fruit Salad", "url": "https://www.allrecipes.com/recipe/214947/perfect-summer-fruit-salad/"},
    ingredients: [[0.6667, "cup", "fresh orange juice"], [0.3333, "cup", "fresh lemon juice"], [0.3333, "cup", "packed brown sugar"], [0.5, "tsp", "grated orange zest"], [0.5, "tsp", "grated lemon zest"], [1.0, "tsp", "vanilla extract"], [2.0, "cups", "cubed fresh pineapple"], [2.0, "cups", "strawberries, hulled and sliced"], [3.0, "", "kiwi fruit, peeled and sliced"], [3.0, "", "bananas, sliced"], [2.0, "", "oranges, peeled and sectioned"], [1.0, "cup", "seedless grapes"], [2.0, "cups", "blueberries"]],
    steps: ["Simmer the orange juice, lemon juice, brown sugar and both zests about 5 minutes, until slightly thick.", "Take off the heat, stir in the vanilla and cool.", "Layer the pineapple, strawberries, kiwi, bananas, oranges, grapes and blueberries in a glass bowl.", "Pour the cooled syrup over, cover and chill 3–4 hours."],
    tips: ["Use honey instead of brown sugar if you prefer."] },
  { id: "energy-bites", kind: "human", course: "Snack", cuisine: "namerican", level: "Easy", emoji: "🟤", title: "No-Bake Energy Bites", time: 15, wait: "1 hour freezing", serves: 24, servesUnit: "bites", tags: ["vegetarian", "no-cook", "make-ahead"], blurb: "Oats, peanut butter, flax and chocolate chips rolled into bites.", kcal: 94, protein: 3, kcalUnit: "bite", rating: 4.8, ratings: 776,
    source: {"site": "Allrecipes", "name": "No-Bake Energy Bites", "url": "https://www.allrecipes.com/recipe/239969/no-bake-energy-bites/"},
    ingredients: [[1.0, "cup", "rolled oats"], [0.5, "cup", "miniature semisweet chocolate chips"], [0.5, "cup", "ground flax seed"], [0.5, "cup", "crunchy peanut butter"], [0.3333, "cup", "honey"], [1.0, "tsp", "vanilla extract"]],
    steps: ["Stir the oats, chocolate chips, flax, peanut butter, honey and vanilla together.", "Roll into 24 balls and set on a tray.", "Freeze about 1 hour until firm. Keep in the fridge or freezer."],
    tips: ["Not for the dog — chocolate is toxic to dogs."] },
  { id: "roast-chickpeas", kind: "human", course: "Snack", cuisine: "namerican", level: "Easy", emoji: "🥜", title: "Roasted Chickpeas", time: 40, wait: "2 hours drying", serves: 4, tags: ["vegan", "gluten-free", "budget"], blurb: "Smoky, crunchy chickpeas — a salty snack with fibre and protein.", kcal: 148, protein: 6, rating: 4.5, ratings: 434,
    source: {"site": "Allrecipes", "name": "Roasted Chickpeas", "url": "https://www.allrecipes.com/recipe/81548/roasted-chickpeas/"},
    ingredients: [[1.0, "can", "chickpeas (garbanzo beans), drained (15 oz)"], [2.0, "tbsp", "olive oil"], [1.0, "pinch", "salt, or to taste"], [0.25, "tsp", "smoked paprika"], [0.25, "tsp", "black pepper"], [1.0, "pinch", "cayenne pepper, or to taste"], [0.125, "tsp", "garlic powder"]],
    steps: ["Blot the chickpeas dry and leave them to air-dry 2 hours (this is what makes them crunchy).", "Heat the oven to 450°F (230°C).", "Toss with olive oil, then the paprika, pepper, cayenne, garlic powder and salt.", "Roast on a rimmed tray 30–40 minutes until crunchy, watching closely near the end."],
    tips: ["Best the day they are made."] },

  /* ───── Reviewed dog treats ───── */
  { id: "dog-pumpkin-biscuits", kind: "dog", course: "Treat", level: "Easy", emoji: "🦴", title: "Peanut Butter & Pumpkin Dog Treats", time: 55, serves: 25, servesUnit: "treats", tags: ["treat", "baked", "freezer"], blurb: "The most-reviewed homemade dog treat on Allrecipes: crunchy and easy.", kcal: 56, kcalUnit: "treat", rating: 4.8, ratings: 1390,
    source: {"site": "Allrecipes", "name": "Homemade Dog Treats (Peanut Butter and Pumpkin)", "url": "https://www.allrecipes.com/recipe/133123/peanut-butter-and-pumpkin-dog-treats/"},
    ingredients: [[2.5, "cups", "whole wheat flour"], [2.0, "", "large eggs"], [0.5, "cup", "canned pumpkin"], [2.0, "tbsp", "peanut butter"], [0.5, "tsp", "salt"], [0.5, "tsp", "ground cinnamon"], [1.0, "tsp", "water, or more if necessary"]],
    steps: ["Heat the oven to 350°F (175°C).", "Mix the flour, eggs, pumpkin, peanut butter, salt and cinnamon.", "Knead by hand until it comes together, adding water a teaspoon at a time only if needed — it should be dry and stiff.", "Roll out about ½ inch thick, cut into ½-inch pieces and put them on a tray.", "Bake about 40 minutes until golden and crunchy. Cool before serving."],
    tips: ["Use plain canned pumpkin, not pie filling.", "Peanut butter must be xylitol-free (also called birch sugar)."] },
  { id: "dog-pb-banana", kind: "dog", course: "Treat", level: "Easy", emoji: "🍌", title: "Peanut Butter & Banana Dog Biscuits", time: 55, serves: 10, servesUnit: "biscuits", tags: ["treat", "baked"], blurb: "Top-rated banana biscuits — cut them into fun shapes.", rating: 4.9, ratings: 425,
    source: {"site": "Allrecipes", "name": "Peanut Butter and Banana Dog Biscuits", "url": "https://www.allrecipes.com/recipe/141532/peanut-butter-and-banana-dog-biscuits/"},
    ingredients: [[1.0, "", "egg"], [0.3333, "cup", "peanut butter"], [0.5, "cup", "mashed banana"], [1.0, "tbsp", "honey"], [1.0, "cup", "whole wheat flour"], [0.5, "cup", "wheat germ"], [1.0, "", "egg white, lightly beaten, for brushing"]],
    steps: ["Heat the oven to 300°F (150°C) and grease a tray.", "Mix the egg, peanut butter, banana and honey well, then stir in the flour and wheat germ.", "Roll ¼ inch thick on a floured board and cut into shapes. Brush with egg white.", "Bake about 30 minutes until dry and golden. Cool on a rack."],
    tips: ["Peanut butter must be xylitol-free.", "Cut small for training-size pieces."] },
  { id: "dog-sweet-potato", kind: "dog", course: "Treat", level: "Easy", emoji: "🍠", title: "Super Simple Sweet Potato Dog Treats", time: 60, serves: 32, servesUnit: "treats", tags: ["treat", "baked"], blurb: "Four ingredients, no peanut butter — good for sensitive dogs.", kcal: 43, kcalUnit: "treat", rating: 4.7, ratings: 142,
    source: {"site": "Allrecipes", "name": "Super Simple Sweet Potato Dog Treats", "url": "https://www.allrecipes.com/recipe/222671/super-simple-sweet-potato-dog-treats/"},
    ingredients: [[1.0, "", "sweet potato"], [2.5, "cups", "whole wheat flour"], [2.0, "", "large eggs"], [0.25, "cup", "unsweetened applesauce"]],
    steps: ["Heat the oven to 350°F (175°C).", "Prick the sweet potato and microwave about 6 minutes until soft. Cool, scoop out and mash about 1 cup.", "Mix in the flour, eggs and applesauce to make a dough.", "Roll ½ inch thick on a floured surface and cut into shapes or strips.", "Bake 35–45 minutes until crisp. Cool completely."],
    tips: ["Unsweetened applesauce only."] },
  { id: "dog-liver", kind: "dog", course: "Treat", level: "Medium", emoji: "🎯", title: "Homemade Dog Liver Bites", time: 50, serves: 50, servesUnit: "bites", tags: ["treat", "high-value", "training", "baked"], blurb: "Soft, irresistible training rewards for recall practice.", kcal: 25, kcalUnit: "bite", rating: 4.9, ratings: 55,
    source: {"site": "Allrecipes", "name": "Homemade Dog Liver Bites", "url": "https://www.allrecipes.com/recipe/265868/homemade-dog-liver-bites/"},
    ingredients: [[1.0, "cup", "rolled oats"], [1.0, "cup", "all-purpose flour"], [0.5, "lb", "chicken livers, rinsed and trimmed"], [2.0, "", "large eggs"], [1.0, "tbsp", "vegetable oil, or more as needed"]],
    steps: ["Heat the oven to 325°F (165°C). Grease a 9-inch square dish and line it with parchment.", "Pulse the oats until fine and mix with the flour.", "Purée the livers, then blend in the eggs and the oil.", "Stir the liver mix into the oats and flour and spread in the dish.", "Bake 30–40 minutes until firm but not crisp. Cool and cut into 50 pieces."],
    tips: ["Liver is rich in vitamin A — a few pieces a day, not handfuls.", "Freeze in bags and take out a day at a time."] },
  { id: "dog-cake", kind: "dog", course: "Treat", level: "Easy", emoji: "🎂", title: "Doggie Birthday Cake", time: 65, serves: 6, servesUnit: "slices", tags: ["treat", "baked", "party"], blurb: "A carrot and peanut butter cake for Oscar's big day.", rating: 4.8, ratings: 658,
    source: {"site": "Allrecipes", "name": "Doggie Birthday Cake", "url": "https://www.allrecipes.com/recipe/141949/doggie-birthday-cake/"},
    ingredients: [[1.0, "", "egg"], [0.3333, "cup", "honey"], [0.25, "cup", "peanut butter"], [0.25, "cup", "cooking oil"], [1.0, "cup", "shredded carrots"], [1.0, "cup", "whole wheat or white flour"], [1.0, "tsp", "baking soda"]],
    steps: ["Heat the oven to 350°F (175°C) and grease a 6-cup ring or bundt pan.", "Blend the egg, honey, peanut butter and oil.", "Stir in the carrots.", "Sift the flour with the baking soda and fold it in.", "Spoon into the pan and bake about 40 minutes, until a toothpick comes out clean. Cool 10 minutes, then turn out."],
    tips: ["We left out the original recipe’s vanilla extract — it is mostly alcohol, which dogs should not have.", "Peanut butter must be xylitol-free.", "A thin slice is plenty — it is a treat, not a meal."] },
  /* RATED:END */

  /* ───── Simmer originals for dogs (vet-standard basics; no online reviews) ───── */
  { id: 'dog-bland-diet', kind: 'dog', course: 'Meal', level: 'Easy', emoji: '🍚', title: 'Chicken & Rice (Upset Tummy)',
    time: 30, serves: 4, servesUnit: 'small meals', tags: ['bland', 'short-term'],
    blurb: 'The classic bland meal vets suggest for a day or two of tummy trouble.',
    ingredients: [[1, 'lb', 'boneless skinless chicken breast'], [1, 'cup', 'white rice (not brown)'], [null, '', 'water — no salt, oil or seasoning']],
    steps: ['Cover the chicken with water in a pot, bring to a boil, then simmer 15–20 minutes until fully cooked.',
      'Lift out the chicken and cook the rice in that broth until very soft.',
      'Shred the chicken finely and remove any fat.',
      'Mix about 1 part chicken to 2 parts rice. Cool completely before serving.',
      'Feed small meals 3–4 times a day, then mix back into the regular food over 2–3 days.'],
    tips: ['Short-term only — it is not a complete diet.', 'Call your vet if vomiting or diarrhea lasts more than a day, there is blood, or your dog is lethargic. Puppies dehydrate quickly.'] },

  { id: 'dog-pupsicles', kind: 'dog', course: 'Treat', level: 'Easy', emoji: '🧊', title: 'Banana Yogurt Pupsicles',
    time: 10, wait: '3 hours freezing', serves: 20, servesUnit: 'cubes', tags: ['treat', 'frozen', 'no-cook', 'teething'],
    blurb: 'Cooling frozen cubes — great for teething puppies and hot days.',
    kcal: 15, kcalUnit: 'cube',
    ingredients: [[1, 'cup', 'plain unsweetened yogurt (no xylitol)'], [1, '', 'ripe banana'], [2, 'tbsp', 'xylitol-free peanut butter']],
    steps: ['Blend or mash everything until smooth.',
      'Spoon into a silicone ice-cube tray or small moulds.',
      'Freeze at least 3 hours. Pop out and serve one at a time outside or on a mat.'],
    tips: ['Some dogs are lactose-sensitive — start with one cube.', 'Swap banana for blueberries or plain pumpkin.'] },

  { id: 'dog-turkey-topper', kind: 'dog', course: 'Topper', level: 'Easy', emoji: '🥕', title: 'Turkey & Veggie Meal Topper',
    time: 25, serves: 14, servesUnit: '¼-cup portions', tags: ['topper', 'freezer'],
    blurb: 'A spoonful on top of kibble makes dinner exciting. Not a complete diet on its own.',
    kcal: 55, kcalUnit: '¼ cup',
    ingredients: [[1, 'lb', 'lean ground turkey'], [1, 'cup', 'carrots, finely grated'], [1, 'cup', 'green beans, chopped small'],
      [0.5, 'cup', 'plain canned pumpkin'], [0.5, 'cup', 'cooked brown rice'], [1, 'cup', 'water']],
    steps: ['Brown the turkey in a dry non-stick pan over medium, breaking it into small pieces. Drain the fat.',
      'Add carrots, green beans and water. Simmer 10 minutes until the veg is soft.',
      'Stir in the pumpkin and rice. Cool completely.',
      'Portion into ¼-cup servings in an ice-cube tray or bags.'],
    tips: ['Fridge 3 days, freezer 2 months.', 'Reduce the kibble a little so total daily calories stay the same.', 'No onion, garlic, salt or seasoning — ever.'] },

  { id: 'dog-salmon-cakes', kind: 'dog', course: 'Treat', level: 'Medium', emoji: '🐟', title: 'Salmon & Sweet Potato Bites',
    time: 35, serves: 30, servesUnit: 'bites', tags: ['treat', 'baked', 'omega-3'],
    blurb: 'Soft, fishy bites dogs go wild for. Good high-value training rewards.',
    kcal: 20, kcalUnit: 'bite',
    ingredients: [[1, 'can', 'salmon in water, no salt added (6 oz), drained'], [1, 'cup', 'mashed cooked sweet potato'],
      [1, '', 'egg'], [0.5, 'cup', 'oat flour']],
    steps: ['Heat the oven to 350°F (175°C) and line a tray.',
      'Mash the salmon (soft canned bones mash in fine) with the sweet potato and egg, then stir in the oat flour.',
      'Roll into small balls (about a teaspoon) and flatten slightly.',
      'Bake 20 minutes until firm. Cool completely.'],
    tips: ['Fridge 5 days, freezer 2 months. Break in half for training.', 'Never feed raw salmon — it can carry a parasite that is dangerous to dogs.'] },

  { id: 'dog-blueberry-carrot', kind: 'dog', course: 'Treat', level: 'Easy', emoji: '🫐', title: 'Blueberry Carrot Frozen Bites',
    time: 10, wait: '2 hours freezing', serves: 24, servesUnit: 'bites', tags: ['treat', 'frozen', 'no-cook', 'teething', 'low-calorie'],
    blurb: 'Light, fruity bites with almost no calories.',
    kcal: 5, kcalUnit: 'bite',
    ingredients: [[0.5, 'cup', 'blueberries'], [1, '', 'carrot, finely grated'], [0.5, 'cup', 'plain unsweetened yogurt'], [0.25, 'cup', 'water']],
    steps: ['Stir everything together.', 'Spoon into a silicone mould and freeze 2 hours.'],
    tips: ['Whole frozen blueberries and baby carrots are good treats on their own, too.'] },

  { id: 'dog-kong', kind: 'dog', course: 'Enrichment', level: 'Easy', emoji: '🧩', title: 'Frozen Stuffed Kong',
    time: 5, wait: 'overnight freezing', serves: 1, servesUnit: 'Kong', tags: ['enrichment', 'frozen', 'teething', 'no-cook'],
    blurb: 'Turns part of dinner into 30+ minutes of calm licking.',
    ingredients: [[0.33, 'of', "your dog's kibble portion, soaked in water 10 minutes"], [1, 'tbsp', 'plain canned pumpkin or plain yogurt'],
      [1, 'tsp', 'xylitol-free peanut butter'], [null, '', 'a few blueberries or carrot pieces']],
    steps: ['Smear a little peanut butter inside to plug the small hole.',
      'Mix the soaked kibble with pumpkin or yogurt and pack it in, adding blueberries as you go.',
      'Seal the top with a thin layer of pumpkin and freeze overnight.',
      'Give it in the crate or on a mat — great for settling down or alone time.'],
    tips: ['Start unfrozen and loosely packed for beginners, then make it harder.', 'Use part of the daily kibble so it does not add calories.'] },

  { id: 'dog-broth', kind: 'dog', course: 'Topper', level: 'Medium', emoji: '🍵', title: 'Dog-Safe Chicken Broth',
    time: 20, wait: '3 hours simmering', serves: 16, servesUnit: '¼-cup portions', tags: ['topper', 'freezer', 'hydration'],
    blurb: 'Plain broth to pour over kibble, freeze into cubes, or stuff in toys.',
    kcal: 10, kcalUnit: '¼ cup',
    ingredients: [[2, 'lb', 'chicken wings, backs or thighs'], [2, '', 'carrots, chopped'], [1, 'stalk', 'celery, chopped'],
      [1, 'tbsp', 'apple cider vinegar'], [10, 'cups', 'water']],
    steps: ['Put everything in a big pot, bring to a boil, then simmer gently, lid ajar, for 3 hours.',
      'Strain through a fine sieve and THROW AWAY every bone — cooked bones splinter.',
      'Chill overnight, then lift off and discard the hardened fat layer.',
      'Freeze in ice-cube trays.'],
    tips: ['Never use store-bought broth unless it says no onion, no garlic and low sodium.'] },

  { id: 'dog-egg-scramble', kind: 'dog', course: 'Topper', level: 'Easy', emoji: '🍳', title: 'Egg & Spinach Scramble',
    time: 5, serves: 2, servesUnit: 'toppers', tags: ['topper', 'quick'],
    blurb: 'A protein boost on top of breakfast kibble, once or twice a week.',
    kcal: 45, kcalUnit: 'topper',
    ingredients: [[1, '', 'egg'], [2, 'tbsp', 'baby spinach, finely chopped'], [null, '', 'no butter, oil, salt or milk']],
    steps: ['Whisk the egg with the spinach.', 'Cook in a dry non-stick pan over low heat, stirring, until fully set.', 'Cool and split into two toppers.'],
    tips: ['Always cook eggs for dogs; raw egg whites can carry salmonella.'] },
];

/* "Can my dog eat…?" Sorted roughly by how often people ask. level: safe |
   caution | toxic. Sources: ASPCA Animal Poison Control and AKC guidance. */
const DOG_FOODS = [
  { food: 'Grapes & raisins', level: 'toxic', note: 'Can cause sudden kidney failure, even in small amounts. Includes currants and sultanas, in baked goods too.' },
  { food: 'Chocolate', level: 'toxic', note: 'Theobromine. Dark and baking chocolate are the most dangerous.' },
  { food: 'Xylitol (birch sugar)', level: 'toxic', note: 'In sugar-free gum, some peanut butters, candy and baked goods. Causes a fast blood-sugar crash and liver failure.' },
  { food: 'Onion, garlic, chives, leeks', level: 'toxic', note: 'Raw, cooked or powdered — damages red blood cells. Check broths, baby food and seasonings.' },
  { food: 'Macadamia nuts', level: 'toxic', note: 'Weakness, vomiting, tremors.' },
  { food: 'Alcohol & raw yeast dough', level: 'toxic', note: 'Dough rises in the stomach and produces alcohol.' },
  { food: 'Coffee, tea, energy drinks', level: 'toxic', note: 'Caffeine affects the heart and nervous system.' },
  { food: 'Cooked bones', level: 'toxic', note: 'Splinter and can tear the gut or cause blockages.' },
  { food: 'Corn on the cob', level: 'toxic', note: 'Kernels are fine; the cob is a classic intestinal blockage.' },
  { food: 'Nutmeg', level: 'toxic', note: 'Myristicin can cause tremors and seizures in larger amounts.' },
  { food: 'Avocado', level: 'caution', note: 'The pit is a choking/blockage hazard and skin/leaves contain persin. A little flesh is not usually a problem but it is fatty — best skipped.' },
  { food: 'Cherries', level: 'caution', note: 'Flesh is OK; pits, stems and leaves contain cyanide and pits can block the gut.' },
  { food: 'Tomatoes', level: 'caution', note: 'Ripe red flesh is fine. Green tomatoes, stems and leaves are toxic.' },
  { food: 'Ham, bacon, sausage', level: 'caution', note: 'Too salty and fatty — can trigger pancreatitis.' },
  { food: 'Milk & ice cream', level: 'caution', note: 'Many dogs are lactose-intolerant. Ice cream also has sugar (and sometimes xylitol or chocolate).' },
  { food: 'Cheese', level: 'caution', note: 'Small pieces are a fine high-value treat for most dogs. High in fat; avoid with garlic/herbs.' },
  { food: 'Raw meat, fish & eggs', level: 'caution', note: 'Bacteria (salmonella, E. coli) and parasites. Raw salmon/trout from the Pacific Northwest can cause deadly salmon poisoning disease.' },
  { food: 'Citrus', level: 'caution', note: 'A segment of orange is OK; peel and seeds upset the stomach.' },
  { food: 'Mushrooms', level: 'caution', note: 'Plain store-bought are OK. Wild mushrooms can be deadly — call a vet if your dog eats one outside.' },
  { food: 'Peanut butter', level: 'caution', note: 'Great treat ONLY if xylitol-free. Read the label every time.' },
  { food: 'Carrots', level: 'safe', note: 'Raw or cooked. Crunchy, low-calorie, good frozen for teething.' },
  { food: 'Blueberries', level: 'safe', note: 'Antioxidants, tiny calories — perfect training treat.' },
  { food: 'Apple', level: 'safe', note: 'Slices are great. Remove the core and seeds.' },
  { food: 'Banana', level: 'safe', note: 'In moderation — high in sugar.' },
  { food: 'Pumpkin (plain)', level: 'safe', note: 'Plain canned or cooked — helps with both loose stools and constipation. Not pie filling (spices, sugar).' },
  { food: 'Sweet potato', level: 'safe', note: 'Cooked and plain. Never raw.' },
  { food: 'Green beans', level: 'safe', note: 'Plain, raw or steamed. A filling low-calorie snack.' },
  { food: 'Cucumber', level: 'safe', note: 'Crunchy, hydrating, almost no calories.' },
  { food: 'Watermelon', level: 'safe', note: 'Seedless flesh only; no rind.' },
  { food: 'Strawberries', level: 'safe', note: 'In moderation.' },
  { food: 'Plain cooked chicken or turkey', level: 'safe', note: 'Boneless, skinless, unseasoned.' },
  { food: 'Cooked eggs', level: 'safe', note: 'Scrambled or boiled, no butter or salt.' },
  { food: 'Cooked salmon', level: 'safe', note: 'Boneless and fully cooked. Never raw.' },
  { food: 'Plain rice & oats', level: 'safe', note: 'Cooked plain. White rice is gentlest on an upset stomach.' },
  { food: 'Plain yogurt', level: 'safe', note: 'Unsweetened, no xylitol. Small amounts.' },
  { food: 'Plain popcorn', level: 'safe', note: 'Air-popped, no butter or salt, no unpopped kernels.' },
  { food: 'Broccoli', level: 'safe', note: 'Small amounts — too much causes gas and stomach upset.' },
];

/* Healthy-eating cheat sheet for the human Guide tab. */
const HUMAN_GUIDE = [
  { title: 'Build a balanced plate', body: 'Half vegetables or fruit, a quarter protein (beans, fish, chicken, tofu, eggs), a quarter whole grains or starchy veg, plus a little healthy fat (olive oil, nuts, avocado). Drink water.' },
  { title: 'Protein at every meal', body: 'Aim for a palm-sized portion (20–30 g). It keeps you full longer and steadies energy through the afternoon.' },
  { title: 'Easy swaps', list: ['Sour cream → plain Greek yogurt', 'White rice → brown rice, quinoa or half cauliflower rice', 'Creamy dressing → olive oil + lemon or vinegar', 'Chips → roasted chickpeas or air-popped popcorn', 'Juice → whole fruit (keeps the fibre)', 'Ground beef → lean turkey or half lentils'] },
  { title: 'Batch it on Sunday', body: 'Cook one grain, roast one tray of veg, prep one protein and one sauce. Mix and match all week: bowls, wraps, salads.' },
  { title: 'Read labels for', list: ['Added sugar (under 10 g per serving is a good target)', 'Sodium (under 600 mg for a meal)', 'Fibre (3 g+ per serving is good)', 'A short ingredient list you recognise'] },
  { title: 'Food safety temperatures', list: ['Chicken & turkey: 165°F / 74°C', 'Ground meat: 160°F / 71°C', 'Fish: 145°F / 63°C', 'Leftovers: eat within 3–4 days'] },
];

/* Treat-budget guidance for the dog Guide tab. Resting energy requirement
   (RER) = 70 × kg^0.75; the multipliers are the standard vet rule of thumb. */
const DOG_LIFE_STAGES = [
  { id: 'pup4', label: 'Puppy, under 4 months', factor: 3.0 },
  { id: 'pup12', label: 'Puppy, 4–12 months', factor: 2.0 },
  { id: 'neutered', label: 'Adult, spayed/neutered', factor: 1.6 },
  { id: 'intact', label: 'Adult, intact', factor: 1.8 },
  { id: 'lose', label: 'Adult, weight loss', factor: 1.0 },
  { id: 'active', label: 'Very active / working', factor: 3.0 },
];

const DOG_RULES = [
  { title: 'The 10% rule', body: 'Treats, toppers and chews should be no more than 10% of daily calories. The rest comes from a complete, balanced food.' },
  { title: 'Homemade full meals', body: 'Home-cooked complete diets need careful balancing (calcium, vitamins, minerals). Use these recipes as treats and toppers, and ask your vet or a veterinary nutritionist before switching to homemade meals.' },
  { title: 'Never add', list: ['Onion, garlic, chives or leeks (any form)', 'Salt, butter, seasoning blends', 'Xylitol / birch sugar', 'Grapes, raisins, chocolate, macadamias'] },
  { title: 'New food? Go slow', body: 'Introduce one new thing at a time in a small amount, and wait a day to check for an upset stomach or itching.' },
  { title: 'Poison emergency', body: 'Call your vet or ASPCA Animal Poison Control (888) 426-4435 right away. Do not make your dog vomit unless a vet tells you to.' },
];
